// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
// Generated by `npm run codegen` from:
//   https://pranithjain.qzz.io/api/v1/openapi.json
//
// Generated at: 2026-06-02T07:13:29.216Z
//
// Re-run `npm run codegen` after changing the OpenAPI spec at
// api/src/lib/openapi.ts. The CI step `npm run codegen:check` will
// fail if this file drifts from the live spec.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly '/api/v1/health': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Service health check
     * @description Returns basic health status. Always returns 200 if the worker is running.
     */
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description Service is healthy */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content: {
            readonly 'application/json': {
              readonly ok?: boolean;
              /** Format: date-time */
              readonly timestamp?: string;
            };
          };
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/health/{dependency}': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Dependency health check
     * @description Check health of specific dependencies: d1, kv, ai, vectorize
     */
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly dependency: PathsApiV1HealthDependencyGetParametersPathDependency;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description Dependency is healthy */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Dependency is unavailable */
        readonly 503: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/ioc/check': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Check IOC reputation
     * @description Check reputation of an IP, domain, URL, or hash across 30+ threat intelligence providers. Returns composite score, admiralty grade, and per-provider verdicts.
     */
    readonly get: {
      readonly parameters: {
        readonly query: {
          /**
           * @description The IOC to check (IP, domain, URL, or hash)
           * @example 8.8.8.8
           */
          readonly indicator: string;
        };
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description IOC check results */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content: {
            readonly 'application/json': {
              readonly indicator?: string;
              /** @enum {string} */
              readonly type?: PathsApiV1IocCheckGetResponses200ContentApplicationJsonType;
              readonly score?: number;
              readonly grade?: string;
              readonly verdicts?: readonly {
                readonly source?: string;
                readonly malicious?: boolean;
                readonly score?: number;
                readonly details?: string;
              }[];
            };
          };
        };
        /** @description Invalid indicator format */
        readonly 400: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Rate limited */
        readonly 429: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/domain/lookup': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Domain intelligence lookup
     * @description Comprehensive domain analysis: DNS records, WHOIS/RDAP, CT logs, SPF/DKIM/DMARC, and threat intel.
     */
    readonly get: {
      readonly parameters: {
        readonly query: {
          /** @example example.com */
          readonly domain: string;
        };
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description Domain intelligence results */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid domain format */
        readonly 400: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/cve/lookup': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * CVE lookup
     * @description Look up a CVE by ID or search by keyword. Returns CVSS score, EPSS probability, CISA KEV status, and references.
     */
    readonly get: {
      readonly parameters: {
        readonly query?: {
          /** @description CVE identifier (e.g., CVE-2024-3094) */
          readonly id?: string;
          /** @description Search keyword (vendor, product, or vulnerability type) */
          readonly q?: string;
        };
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description CVE details */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid parameters */
        readonly 400: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/ip-geo': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * IP geolocation and reputation
     * @description Get IP geolocation, ASN, company, and privacy detection (VPN/proxy/tor/hosting).
     */
    readonly get: {
      readonly parameters: {
        readonly query: {
          /** @example 8.8.8.8 */
          readonly ip: string;
        };
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description IP intelligence results */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/phishing/analyze': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Analyze email for phishing
     * @description Parse raw email source for phishing indicators. Checks SPF/DKIM/DMARC, extracts URLs, computes risk score.
     */
    readonly post: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'text/plain': string;
        };
      };
      readonly responses: {
        /** @description Phishing analysis results */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/briefings/today': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Today's threat briefing
     * @description Get today's threat intelligence briefing with CVEs, ransomware activity, and emerging threats.
     */
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description Daily briefing */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/ransomware/recent': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Recent ransomware activity
     * @description Latest ransomware victims, group activity, and leak-site posts.
     */
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description Ransomware activity data */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/unified-search': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Unified cross-source search
     * @description Search across all threat intelligence feeds by keyword, IOC, actor, malware, or CVE.
     */
    readonly get: {
      readonly parameters: {
        readonly query: {
          readonly q: string;
        };
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description Search results across all sources */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/v1/openapi.json': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * OpenAPI specification
     * @description Returns this OpenAPI 3.1 specification in JSON format.
     */
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: {
        /** @description OpenAPI spec */
        readonly 200: {
          headers: {
            readonly [name: string]: unknown;
          };
          content: {
            readonly 'application/json': Record<string, never>;
          };
        };
      };
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: {
    /** @description Missing or invalid authentication */
    readonly Unauthorized: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly 'application/json': {
          /** @example unauthorized */
          readonly error?: string;
          /** @example api key required */
          readonly message?: string;
        };
      };
    };
    /** @description Rate limit exceeded */
    readonly RateLimited: {
      headers: {
        /** @description Seconds until rate limit resets */
        readonly 'Retry-After'?: number;
        readonly [name: string]: unknown;
      };
      content: {
        readonly 'application/json': {
          /** @example rate_limited */
          readonly error?: string;
          readonly message?: string;
          readonly limit?: number;
          readonly window_seconds?: number;
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsApiV1HealthDependencyGetParametersPathDependency {
  d1 = 'd1',
  kv = 'kv',
  ai = 'ai',
  vectorize = 'vectorize',
}
export enum PathsApiV1IocCheckGetResponses200ContentApplicationJsonType {
  ipv4 = 'ipv4',
  ipv6 = 'ipv6',
  domain = 'domain',
  url = 'url',
  hash = 'hash',
  email = 'email',
}
export type operations = Record<string, never>;
