export type Severity = 'critical' | 'high' | 'medium' | 'low' | 'info';

export interface ScannerHit {
  severity: Severity;
  ruleId: string;
  kind: string;
  message: string;
  line: number;
  column: number;
  snippet: string;
  recommendation: string;
}

export interface ScannerRule {
  id: string;
  name: string;
  kind: string;
  severity: Severity;
  languages: string[];
  pattern: RegExp;
  message: string;
  recommendation: string;
  cwe?: string;
}

const SEVERITY_ORDER: Record<Severity, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
  info: 4,
};

export function severityOrder(s: Severity): number {
  return SEVERITY_ORDER[s];
}

// ---------------------------------------------------------------------------
// Python SAST rules
// ---------------------------------------------------------------------------
export const PYTHON_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-PY-001',
    name: 'eval() usage',
    kind: 'code-injection',
    severity: 'critical',
    languages: ['python'],
    pattern: /\beval\s*\(/g,
    message: 'Use of eval() allows arbitrary code execution',
    recommendation: 'Replace eval() with ast.literal_eval() or a proper parser',
    cwe: 'CWE-95',
  },
  {
    id: 'MEDUSA-PY-002',
    name: 'exec() usage',
    kind: 'code-injection',
    severity: 'critical',
    languages: ['python'],
    pattern: /\bexec\s*\(/g,
    message: 'Use of exec() allows arbitrary code execution',
    recommendation: 'Remove exec() calls; use a safe alternative',
    cwe: 'CWE-95',
  },
  {
    id: 'MEDUSA-PY-003',
    name: 'subprocess with shell=True',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['python'],
    pattern: /subprocess\.\w+\s*\([^)]*shell\s*=\s*True/g,
    message: 'shell=True enables shell injection via subprocess',
    recommendation: 'Use shell=False (default) and pass args as a list',
    cwe: 'CWE-78',
  },
  {
    id: 'MEDUSA-PY-004',
    name: 'os.system() / os.popen()',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['python'],
    pattern: /\bos\.(?:system|popen)\s*\(/g,
    message: 'Shell function invocation can lead to command injection',
    recommendation: 'Use subprocess.run() with shell=False',
    cwe: 'CWE-78',
  },
  {
    id: 'MEDUSA-PY-005',
    name: 'pickle.loads()',
    kind: 'deserialization',
    severity: 'high',
    languages: ['python'],
    pattern: /\bpickle\.(?:loads?|unpickle)\s*\(/g,
    message: 'pickle deserialization can execute arbitrary code',
    recommendation: 'Use a safe serialization format like JSON or msgpack',
    cwe: 'CWE-502',
  },
  {
    id: 'MEDUSA-PY-006',
    name: 'yaml.load() without SafeLoader',
    kind: 'deserialization',
    severity: 'high',
    languages: ['python'],
    pattern: /\byaml\.load\s*\(/g,
    message: 'yaml.load() without SafeLoader can execute arbitrary code',
    recommendation: 'Use yaml.safe_load() or yaml.load(..., Loader=yaml.SafeLoader)',
    cwe: 'CWE-502',
  },
  {
    id: 'MEDUSA-PY-007',
    name: 'SQL string concatenation',
    kind: 'sql-injection',
    severity: 'critical',
    languages: ['python'],
    pattern: /(?:execute|executemany|cursor\.execute)\s*\(\s*['"][^'"]*?(?:%s|%\(|f['"][^'"]*\{)/gi,
    message: 'SQL query built with string formatting — possible injection',
    recommendation: 'Use parameterized queries / prepared statements',
    cwe: 'CWE-89',
  },
  {
    id: 'MEDUSA-PY-008',
    name: 'request.get/post without timeout',
    kind: 'network',
    severity: 'medium',
    languages: ['python'],
    pattern: /(?:requests|httpx|aiohttp)\.(?:get|post|put|delete|patch)\s*\((?!.*timeout)/g,
    message: 'HTTP request without timeout may hang indefinitely',
    recommendation: 'Always set a timeout parameter (e.g. timeout=30)',
    cwe: 'CWE-400',
  },
  {
    id: 'MEDUSA-PY-009',
    name: 'assert in non-test code',
    kind: 'misconfiguration',
    severity: 'medium',
    languages: ['python'],
    pattern: /^assert\s/gm,
    message: 'assert statements are removed with python -O (optimized mode)',
    recommendation: 'Use proper if/raise checks for validation in production code',
    cwe: 'CWE-670',
  },
  {
    id: 'MEDUSA-PY-010',
    name: 'mktemp usage',
    kind: 'file-system',
    severity: 'high',
    languages: ['python'],
    pattern: /\btempfile\.mktemp\b|\bmktemp\b/g,
    message: 'mktemp creates predictable temp files (race condition)',
    recommendation: 'Use tempfile.mkstemp() or tempfile.TemporaryFile() instead',
    cwe: 'CWE-367',
  },
  {
    id: 'MEDUSA-PY-011',
    name: 'Jinja2 template with autoescape off',
    kind: 'xss',
    severity: 'high',
    languages: ['python'],
    pattern: /jinja2?\s*\.\s*(?:Environment|Template)\s*\([^)]*autoescape\s*=\s*False/g,
    message: 'Autoescape disabled in Jinja2 template engine',
    recommendation: 'Enable autoescape=True or manually escape all variables',
    cwe: 'CWE-79',
  },
  {
    id: 'MEDUSA-PY-012',
    name: 'Django DEBUG=True',
    kind: 'misconfiguration',
    severity: 'high',
    languages: ['python'],
    pattern: /DEBUG\s*=\s*True/g,
    message: 'Django DEBUG mode enabled in what appears to be a production config',
    recommendation: 'Set DEBUG=False in production and use proper error pages',
    cwe: 'CWE-489',
  },
  {
    id: 'MEDUSA-PY-013',
    name: 'Hardcoded password in source',
    kind: 'hardcoded-secret',
    severity: 'medium',
    languages: ['python'],
    pattern: /(?:password|passwd|pwd)\s*[:=]\s*['\"][^'\"]{6,}['\"]/gi,
    message: 'Potential hardcoded password detected',
    recommendation: 'Use environment variables or a secrets manager',
    cwe: 'CWE-798',
  },
  {
    id: 'MEDUSA-PY-014',
    name: 'Flask SECRET_KEY hardcoded',
    kind: 'hardcoded-secret',
    severity: 'critical',
    languages: ['python'],
    pattern: /SECRET_KEY\s*=\s*['\"][a-zA-Z0-9_\-]{5,}['\"]/g,
    message: 'Flask SECRET_KEY appears hardcoded in source',
    recommendation: 'Generate a random key and load it from environment variables',
    cwe: 'CWE-798',
  },
];

// ---------------------------------------------------------------------------
// JavaScript / TypeScript SAST rules
// ---------------------------------------------------------------------------
export const JAVASCRIPT_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-JS-001',
    name: 'eval() usage',
    kind: 'code-injection',
    severity: 'critical',
    languages: ['javascript', 'typescript'],
    pattern: /\beval\s*\(/g,
    message: 'eval() allows arbitrary code execution',
    recommendation: 'Avoid eval(); use Function() constructor cautiously or safer alternatives',
    cwe: 'CWE-95',
  },
  {
    id: 'MEDUSA-JS-002',
    name: 'innerHTML assignment',
    kind: 'xss',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /\.innerHTML\s*=(?!=)/g,
    message: 'innerHTML assignment can lead to XSS if content includes user input',
    recommendation: 'Use textContent or insertAdjacentHTML with sanitized input',
    cwe: 'CWE-79',
  },
  {
    id: 'MEDUSA-JS-003',
    name: 'document.write()',
    kind: 'xss',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /\bdocument\.write\s*\(/g,
    message: 'document.write() is dangerous and can overwrite the page',
    recommendation: 'Use DOM manipulation methods instead',
    cwe: 'CWE-79',
  },
  {
    id: 'MEDUSA-JS-004',
    name: 'new Function()',
    kind: 'code-injection',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /\bnew\s+Function\s*\(/g,
    message: 'Function constructor is similar to eval() and allows code injection',
    recommendation: 'Avoid dynamic code creation; use predefined functions',
    cwe: 'CWE-94',
  },
  {
    id: 'MEDUSA-JS-005',
    name: 'setTimeout with string arg',
    kind: 'code-injection',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /\bsetTimeout\s*\(\s*['"`]/g,
    message: 'Passing a string to setTimeout is like eval()',
    recommendation: 'Pass a function reference instead of a string',
    cwe: 'CWE-94',
  },
  {
    id: 'MEDUSA-JS-006',
    name: 'SQL injection via template literal',
    kind: 'sql-injection',
    severity: 'critical',
    languages: ['javascript', 'typescript'],
    pattern: /(?:execute|query|run|all|get)\s*\(\s*[`'"]/gi,
    message: 'SQL query built with string interpolation — possible injection',
    recommendation: 'Use parameterized queries with ? or $1 placeholders',
    cwe: 'CWE-89',
  },
  {
    id: 'MEDUSA-JS-007',
    name: 'Insecure crypto random',
    kind: 'crypto',
    severity: 'medium',
    languages: ['javascript', 'typescript'],
    pattern: /\bMath\.random\b/g,
    message: 'Math.random() is not cryptographically secure',
    recommendation: 'Use crypto.getRandomValues() for security-sensitive randomness',
    cwe: 'CWE-338',
  },
  {
    id: 'MEDUSA-JS-008',
    name: 'Hardcoded JWT secret',
    kind: 'hardcoded-secret',
    severity: 'critical',
    languages: ['javascript', 'typescript'],
    pattern: /jwt\s*(?:\.\w*)?secret\s*[:=]\s*['\"][^'\"]{3,}['\"]/gi,
    message: 'JWT secret appears hardcoded in source',
    recommendation: 'Load JWT secret from environment variables',
    cwe: 'CWE-798',
  },
  {
    id: 'MEDUSA-JS-009',
    name: 'CORS wildcard origin',
    kind: 'misconfiguration',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /(?:Access-Control-Allow-Origin|cors)\s*[:=]\s*['"`]\*['"`]/gi,
    message: 'Wildcard CORS origin allows any site to make cross-origin requests',
    recommendation: 'Restrict Access-Control-Allow-Origin to specific origins',
    cwe: 'CWE-942',
  },
  {
    id: 'MEDUSA-JS-010',
    name: 'Insecure cookie flags',
    kind: 'misconfiguration',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /cookie\s*[:=][^{]*[^;]*(?:secure|httponly|samesite)(?!\s*[:=]\s*(?:true|strict|lax))/gi,
    message: 'Cookie set without secure/httpOnly/SameSite flags',
    recommendation: 'Set Secure, HttpOnly, and SameSite=Strict on cookies',
    cwe: 'CWE-614',
  },
  {
    id: 'MEDUSA-JS-011',
    name: 'Command injection via exec/spawn',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['javascript', 'typescript'],
    pattern: /(?:exec|execSync|spawn)\s*\([^)]*\+/g,
    message: 'Command execution with string concatenation — possible injection',
    recommendation: 'Use execFile() or spawn() with args array instead of shell string',
    cwe: 'CWE-78',
  },
  {
    id: 'MEDUSA-JS-012',
    name: 'NoSQL injection risk',
    kind: 'injection',
    severity: 'high',
    languages: ['javascript', 'typescript'],
    pattern: /\.find\s*\(\s*\{[^}]*\$/g,
    message: 'MongoDB $-operator in query may be vulnerable to NoSQL injection',
    recommendation: 'Validate and sanitize user input before passing to queries',
    cwe: 'CWE-943',
  },
];

// ---------------------------------------------------------------------------
// Go SAST rules
// ---------------------------------------------------------------------------
export const GO_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-GO-001',
    name: 'SQL injection via fmt.Sprintf',
    kind: 'sql-injection',
    severity: 'critical',
    languages: ['go'],
    pattern: /fmt\.Sprintf\s*\([^)]*?(?:SELECT|INSERT|UPDATE|DELETE)\b/gi,
    message: 'SQL query built with string formatting — possible injection',
    recommendation: 'Use parameterized queries with ? or $N placeholders via database/sql',
    cwe: 'CWE-89',
  },
  {
    id: 'MEDUSA-GO-002',
    name: 'Insecure TLS',
    kind: 'crypto',
    severity: 'high',
    languages: ['go'],
    pattern: /InsecureSkipVerify\s*:\s*true/g,
    message: 'TLS certificate verification disabled',
    recommendation: 'Set InsecureSkipVerify to false and use proper certificates',
    cwe: 'CWE-295',
  },
  {
    id: 'MEDUSA-GO-003',
    name: 'exec.Command with user input',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['go'],
    pattern: /exec\.Command\s*\([^)]*?(?:os\.Args|r\.FormValue|r\.URL)/g,
    message: 'Command execution with user-controlled input',
    recommendation: 'Validate/sanitize input and avoid passing user data to shell commands',
    cwe: 'CWE-78',
  },
  {
    id: 'MEDUSA-GO-004',
    name: 'Weak hash (MD5/SHA1)',
    kind: 'crypto',
    severity: 'medium',
    languages: ['go'],
    pattern: /(?:md5|sha1)\.(?:New|Sum|Create)\b/g,
    message: 'Use of weak hashing algorithm',
    recommendation: 'Use SHA-256 or stronger for hashing; use bcrypt/argon2 for passwords',
    cwe: 'CWE-327',
  },
  {
    id: 'MEDUSA-GO-005',
    name: 'Hardcoded credential',
    kind: 'hardcoded-secret',
    severity: 'high',
    languages: ['go'],
    pattern: /(?:password|secret|apiKey|token)\s*(?::|=)\s*["`][^"`]{8,}["`]/gi,
    message: 'Hardcoded credential in source code',
    recommendation: 'Use environment variables or a secrets manager',
    cwe: 'CWE-798',
  },
  {
    id: 'MEDUSA-GO-006',
    name: 'OS command injection via exec.Command',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['go'],
    pattern: /exec\.Command\s*\(\s*["`](?:bash|sh|cmd|powershell)["`]/g,
    message: 'Shell execution via exec.Command',
    recommendation: 'Avoid spawning shells; use Go native libraries instead',
    cwe: 'CWE-78',
  },
];

// ---------------------------------------------------------------------------
// Rust SAST rules (Medusa's native Rust rules)
// ---------------------------------------------------------------------------
export const RUST_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-RS-001',
    name: 'unwrap() usage',
    kind: 'error-handling',
    severity: 'medium',
    languages: ['rust'],
    pattern: /\.unwrap\(\)/g,
    message: 'unwrap() will panic on Err — use pattern matching or ? operator',
    recommendation: 'Use pattern matching, ? operator, or expect() with a descriptive message',
    cwe: 'CWE-754',
  },
  {
    id: 'MEDUSA-RS-002',
    name: 'expect() usage',
    kind: 'error-handling',
    severity: 'low',
    languages: ['rust'],
    pattern: /\.expect\(/g,
    message: 'expect() will panic — consider proper error handling',
    recommendation: 'Return Result instead of panicking where possible',
    cwe: 'CWE-754',
  },
  {
    id: 'MEDUSA-RS-003',
    name: 'TLS verification disabled',
    kind: 'crypto',
    severity: 'high',
    languages: ['rust'],
    pattern: /dangerous_accept_invalid_certs\s*\(?\s*true\)?/g,
    message: 'TLS certificate verification disabled',
    recommendation: 'Enable certificate verification in production',
    cwe: 'CWE-295',
  },
  {
    id: 'MEDUSA-RS-004',
    name: 'Command injection via std::process',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['rust'],
    pattern: /Command\s*::\s*new\s*\(\s*["`](?:sh|bash|cmd|powershell)["`]/g,
    message: 'Shell execution via std::process::Command',
    recommendation: 'Avoid shell invocation; use Rust native libraries',
    cwe: 'CWE-78',
  },
  {
    id: 'MEDUSA-RS-005',
    name: 'Unsafe deserialization',
    kind: 'deserialization',
    severity: 'high',
    languages: ['rust'],
    pattern: /serde_json::from_str\s*<[^>]*>/g,
    message: 'Generic deserialization from untrusted input',
    recommendation: 'Validate JSON structure before deserializing untrusted data',
    cwe: 'CWE-502',
  },
  {
    id: 'MEDUSA-RS-006',
    name: 'Raw pointer dereference',
    kind: 'memory-safety',
    severity: 'high',
    languages: ['rust'],
    pattern: /unsafe\s*\{[^}]*?\*.*\b(?:as_mut_ptr|as_ptr)\b/g,
    message: 'Unsafe raw pointer dereference — memory safety risk',
    recommendation: 'Minimize unsafe blocks; use safe abstractions',
    cwe: 'CWE-119',
  },
  {
    id: 'MEDUSA-RS-007',
    name: 'Weak crypto',
    kind: 'crypto',
    severity: 'medium',
    languages: ['rust'],
    pattern: /\bmd5\b|\bsha1\b/g,
    message: 'Use of weak cryptographic algorithm',
    recommendation: 'Use SHA-256, SHA-3, or argon2/bcrypt for password hashing',
    cwe: 'CWE-327',
  },
  {
    id: 'MEDUSA-RS-008',
    name: 'Format string vulnerability',
    kind: 'injection',
    severity: 'medium',
    languages: ['rust'],
    pattern: /format!\s*\([^)]*\{[^}]*\}.*\.as_str\(\)/g,
    message: 'Format string constructed from potentially unsafe input',
    recommendation: 'Avoid passing user input directly to format!()',
    cwe: 'CWE-134',
  },
];

// ---------------------------------------------------------------------------
// PHP SAST rules (Medusa's native PHP rules)
// ---------------------------------------------------------------------------
export const PHP_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-PHP-001',
    name: 'mysql_* / mysqli_* raw query',
    kind: 'sql-injection',
    severity: 'critical',
    languages: ['php'],
    pattern: /mysql(?:i)?_(?:query|real_query|multi_query)\s*\([^)]*\$/g,
    message: 'SQL query built with variable interpolation — possible injection',
    recommendation: 'Use prepared statements with PDO or mysqli prepared queries',
    cwe: 'CWE-89',
  },
  {
    id: 'MEDUSA-PHP-002',
    name: 'eval() usage',
    kind: 'code-injection',
    severity: 'critical',
    languages: ['php'],
    pattern: /\beval\s*\(/g,
    message: 'eval() allows arbitrary PHP code execution',
    recommendation: 'Remove eval() calls; there is almost always a better approach',
    cwe: 'CWE-95',
  },
  {
    id: 'MEDUSA-PHP-003',
    name: 'unserialize() from user input',
    kind: 'deserialization',
    severity: 'critical',
    languages: ['php'],
    pattern: /\bunserialize\s*\(\s*(?:\$_|(?:file_get_contents|fgets?)\s*\(\s*(?:\$_)?)/g,
    message: 'unserialize() on user-controlled input can lead to object injection',
    recommendation: 'Use json_decode() instead of unserialize()',
    cwe: 'CWE-502',
  },
  {
    id: 'MEDUSA-PHP-004',
    name: 'include/require with variable',
    kind: 'lfi',
    severity: 'high',
    languages: ['php'],
    pattern: /(?:include|require)(?:_once)?\s*\(\s*(?:\$|\.|\$_GET|\$_POST|\$_REQUEST)/g,
    message: 'Dynamic file inclusion — Local File Inclusion (LFI) risk',
    recommendation: 'Use a whitelist of allowed files or a router instead',
    cwe: 'CWE-98',
  },
  {
    id: 'MEDUSA-PHP-005',
    name: 'shell_exec / exec / system',
    kind: 'command-injection',
    severity: 'critical',
    languages: ['php'],
    pattern: /\b(?:shell_exec|exec|system|passthru|popen|proc_open|pcntl_exec)\s*\(/g,
    message: 'Shell execution function — command injection risk',
    recommendation: 'Avoid shell functions; use PHP-native alternatives',
    cwe: 'CWE-78',
  },
  {
    id: 'MEDUSA-PHP-006',
    name: 'Reflected XSS via raw echo',
    kind: 'xss',
    severity: 'high',
    languages: ['php'],
    pattern: /echo\s+\$_(?:GET|POST|REQUEST|SERVER\[)/g,
    message: 'Directly outputting user input — reflected XSS risk',
    recommendation: 'Use htmlspecialchars() when outputting user-controlled data',
    cwe: 'CWE-79',
  },
  {
    id: 'MEDUSA-PHP-007',
    name: 'Path traversal in file operations',
    kind: 'path-traversal',
    severity: 'high',
    languages: ['php'],
    pattern: /(?:file_get_contents|file_put_contents|unlink|fopen|fwrite)\s*\(\s*(?:\$)/g,
    message: 'File operation with variable path — path traversal risk',
    recommendation: 'Validate and sanitize file paths; use basename() and realpath()',
    cwe: 'CWE-22',
  },
  {
    id: 'MEDUSA-PHP-008',
    name: 'SSRF via file_get_contents URL',
    kind: 'ssrf',
    severity: 'high',
    languages: ['php'],
    pattern: /file_get_contents\s*\(\s*(?:\$_(?:GET|POST)|\$_REQUEST)/g,
    message: 'SSRF — fetching URL from user input can be abused',
    recommendation: 'Validate and restrict URLs to an allowlist',
    cwe: 'CWE-918',
  },
  {
    id: 'MEDUSA-PHP-009',
    name: 'move_uploaded_file without validation',
    kind: 'file-upload',
    severity: 'high',
    languages: ['php'],
    pattern: /move_uploaded_file\s*\(/g,
    message: 'Unrestricted file upload — RCE risk',
    recommendation: 'Validate file type (MIME + extension), size, and store outside webroot',
    cwe: 'CWE-434',
  },
];

// ---------------------------------------------------------------------------
// Infrastructure-as-Code (Terraform / K8s / Docker)
// ---------------------------------------------------------------------------
export const IAC_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-IAC-001',
    name: 'S3 bucket public access',
    kind: 'cloud-misconfig',
    severity: 'critical',
    languages: ['terraform'],
    pattern:
      /(?:acl\s*=\s*"public-read"|acl\s*=\s*"public-read-write"|acl\s*=\s*"authenticated-read"|block_public_acls\s*=\s*false|block_public_policy\s*=\s*false)/g,
    message: 'S3 bucket has public access enabled',
    recommendation: 'Set acl to "private" and enable all block_public_* settings',
    cwe: 'CWE-200',
  },
  {
    id: 'MEDUSA-IAC-002',
    name: 'Security group ingress 0.0.0.0/0',
    kind: 'cloud-misconfig',
    severity: 'critical',
    languages: ['terraform'],
    pattern: /cidr_blocks\s*=\s*\[?\s*["']0\.0\.0\.0\/0["']/g,
    message: 'Security group allows traffic from any IP (0.0.0.0/0)',
    recommendation: 'Restrict ingress CIDR blocks to specific trusted IPs',
    cwe: 'CWE-200',
  },
  {
    id: 'MEDUSA-IAC-003',
    name: 'EKS cluster public endpoint',
    kind: 'cloud-misconfig',
    severity: 'high',
    languages: ['terraform'],
    pattern: /endpoint_public_access\s*=\s*true/g,
    message: 'Kubernetes API endpoint is publicly accessible',
    recommendation: 'Set endpoint_public_access = false or restrict via endpoint_public_access_cidrs',
    cwe: 'CWE-200',
  },
  {
    id: 'MEDUSA-IAC-004',
    name: 'RDS publicly accessible',
    kind: 'cloud-misconfig',
    severity: 'critical',
    languages: ['terraform'],
    pattern: /publicly_accessible\s*=\s*true/g,
    message: 'RDS instance is publicly accessible',
    recommendation: 'Set publicly_accessible = false and use a VPN or bastion host',
    cwe: 'CWE-200',
  },
  {
    id: 'MEDUSA-IAC-005',
    name: 'IAM wildcard action',
    kind: 'iam',
    severity: 'high',
    languages: ['terraform'],
    pattern: /actions\s*=\s*\[?\s*["']\*["']/g,
    message: 'IAM policy grants wildcard ("*") action — over-privileged',
    recommendation: 'Scope IAM actions to the minimum required permissions',
    cwe: 'CWE-269',
  },
  {
    id: 'MEDUSA-IAC-006',
    name: 'Docker container runs as root',
    kind: 'docker',
    severity: 'high',
    languages: ['dockerfile'],
    pattern: /^(?!.*USER\s)/gm,
    message: 'No USER directive — container will run as root by default',
    recommendation: 'Add a USER directive to run as non-root user',
    cwe: 'CWE-250',
  },
  {
    id: 'MEDUSA-IAC-007',
    name: 'Hardcoded secret in Docker ARG/ENV',
    kind: 'hardcoded-secret',
    severity: 'high',
    languages: ['dockerfile'],
    pattern: /(?:ENV|ARG)\s+\w*(?:PASSWD|SECRET|TOKEN|KEY|CREDENTIAL)\s*=/gi,
    message: 'Credential may be embedded in Docker image layer',
    recommendation: 'Use --build-arg with CI secrets or Docker secrets at runtime',
    cwe: 'CWE-798',
  },
  {
    id: 'MEDUSA-IAC-008',
    name: 'privileged container',
    kind: 'docker',
    severity: 'critical',
    languages: ['dockerfile', 'kubernetes'],
    pattern: /privileged\s*:\s*true/g,
    message: 'Container running in privileged mode — full host access',
    recommendation: 'Drop --privileged and add only required capabilities',
    cwe: 'CWE-250',
  },
  {
    id: 'MEDUSA-IAC-009',
    name: 'K8s runAsNonRoot not set',
    kind: 'kubernetes',
    severity: 'high',
    languages: ['kubernetes'],
    pattern: /runAsNonRoot\s*:\s*false/g,
    message: 'Security context allows running as root',
    recommendation: 'Set runAsNonRoot: true and runAsUser to >10000',
    cwe: 'CWE-250',
  },
];

// ---------------------------------------------------------------------------
// Secret scanner patterns (port of Medusa's secret_patterns.py)
// ---------------------------------------------------------------------------
export const SECRET_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-SECRET-ANTHROPIC',
    name: 'Anthropic API key',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /sk-ant-(?:api03|admin01)-[A-Za-z0-9_\-]{80,}/g,
    message: 'Anthropic Claude API key detected',
    recommendation: 'Revoke this key immediately via console.anthropic.com',
  },
  {
    id: 'MEDUSA-SECRET-OPENAI',
    name: 'OpenAI API key',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bsk-(?!ant-)(?:proj-|svcacct-|admin-)?[A-Za-z0-9_\-]{40,}\b/g,
    message: 'OpenAI API key detected',
    recommendation: 'Revoke via platform.openai.com/api-keys',
  },
  {
    id: 'MEDUSA-SECRET-AWS-ACCESS',
    name: 'AWS Access Key ID',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\b(?:AKIA|ASIA|AGPA|AROA|AIPA|ANPA|ANVA|ABIA|ACCA)[0-9A-Z]{16}\b/g,
    message: 'AWS Access Key ID detected',
    recommendation: 'Revoke via AWS IAM console and rotate credentials',
  },
  {
    id: 'MEDUSA-SECRET-AWS-SECRET',
    name: 'AWS Secret Access Key',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /aws.{0,20}?(?:secret|sk).{0,3}['"=:\s]+([A-Za-z0-9/+]{40})\b/gi,
    message: 'AWS Secret Access Key detected',
    recommendation: 'Revoke via AWS IAM console immediately',
  },
  {
    id: 'MEDUSA-SECRET-GITHUB-PAT',
    name: 'GitHub PAT (classic)',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bghp_[A-Za-z0-9]{36}\b/g,
    message: 'GitHub Personal Access Token (classic) detected',
    recommendation: 'Revoke via GitHub Settings > Developer settings > Personal access tokens',
  },
  {
    id: 'MEDUSA-SECRET-GITHUB-FINEGRAINED',
    name: 'GitHub fine-grained PAT',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bgithub_pat_[A-Za-z0-9_]{82}\b/g,
    message: 'GitHub fine-grained PAT detected',
    recommendation: 'Revoke via GitHub Settings > Developer settings > Fine-grained tokens',
  },
  {
    id: 'MEDUSA-SECRET-GITHUB-OAUTH',
    name: 'GitHub OAuth token',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bgho_[A-Za-z0-9]{36}\b/g,
    message: 'GitHub OAuth access token detected',
    recommendation: 'Revoke via GitHub Settings > Applications > Authorized OAuth Apps',
  },
  {
    id: 'MEDUSA-SECRET-GITLAB-PAT',
    name: 'GitLab PAT',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bglpat-[A-Za-z0-9_\-]{20,}\b/g,
    message: 'GitLab Personal Access Token detected',
    recommendation: 'Revoke via GitLab Profile > Access Tokens',
  },
  {
    id: 'MEDUSA-SECRET-PYPI',
    name: 'PyPI API token',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /pypi-AgE[A-Za-z0-9_\-]{50,}/g,
    message: 'PyPI API token detected — can publish packages as you',
    recommendation: 'Revoke via pypi.org/manage/account/token/',
  },
  {
    id: 'MEDUSA-SECRET-NPM',
    name: 'npm access token',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\bnpm_[A-Za-z0-9]{36}\b/g,
    message: 'npm access token detected',
    recommendation: 'Revoke via npmjs.com/settings/tokens',
  },
  {
    id: 'MEDUSA-SECRET-STRIPE-LIVE',
    name: 'Stripe live secret key',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bsk_live_[A-Za-z0-9]{24,}\b/g,
    message: 'Stripe live secret key detected — can charge real cards',
    recommendation: 'Revoke via dashboard.stripe.com/apikeys immediately',
  },
  {
    id: 'MEDUSA-SECRET-STRIPE-RESTRICTED',
    name: 'Stripe restricted key',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\brk_live_[A-Za-z0-9]{24,}\b/g,
    message: 'Stripe restricted key detected',
    recommendation: 'Revoke via dashboard.stripe.com/apikeys',
  },
  {
    id: 'MEDUSA-SECRET-SLACK-BOT',
    name: 'Slack bot/user token',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\bxox[bpoa]-\d+-\d+-[A-Za-z0-9]{20,}\b/g,
    message: 'Slack bot or user token detected',
    recommendation: 'Revoke via api.slack.com/apps',
  },
  {
    id: 'MEDUSA-SECRET-HUGGINGFACE',
    name: 'HuggingFace token',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\bhf_[A-Za-z0-9]{30,}\b/g,
    message: 'HuggingFace API token detected',
    recommendation: 'Revoke via huggingface.co/settings/tokens',
  },
  {
    id: 'MEDUSA-SECRET-SENDGRID',
    name: 'SendGrid API key',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\bSG\.[A-Za-z0-9_\-]{20,}\.[A-Za-z0-9_\-]{40,}\b/g,
    message: 'SendGrid API key detected',
    recommendation: 'Revoke via app.sendgrid.com/settings/api_keys',
  },
  {
    id: 'MEDUSA-SECRET-TWILIO',
    name: 'Twilio API key',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\bSK[a-f0-9]{32}\b/g,
    message: 'Twilio API key SID detected',
    recommendation: 'Revoke via console.twilio.com',
  },
  {
    id: 'MEDUSA-SECRET-DISCORD-WEBHOOK',
    name: 'Discord webhook URL',
    kind: 'webhook',
    severity: 'high',
    languages: ['all'],
    pattern:
      /https:\/\/(?:discord(?:app)?\.com|canary\.discord\.com|ptb\.discord\.com)\/api\/webhooks\/\d{17,20}\/[A-Za-z0-9_\-]{60,}/g,
    message: 'Discord webhook URL detected — can be used to post messages',
    recommendation: 'Delete the webhook from Discord server settings > Integrations',
  },
  {
    id: 'MEDUSA-SECRET-PRIVATE-KEY',
    name: 'Private key (PEM)',
    kind: 'private-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /-----BEGIN (?:RSA |DSA |EC |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY-----/g,
    message: 'Private key detected in source',
    recommendation: 'Remove private keys from code; use a secrets manager or SSH agent',
    cwe: 'CWE-312',
  },
  {
    id: 'MEDUSA-SECRET-DB-URI',
    name: 'Database URI with credentials',
    kind: 'database-uri',
    severity: 'high',
    languages: ['all'],
    pattern: /\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis|amqp|mssql):\/\/[^:\s/'"]+:[^@\s'"]+@/g,
    message: 'Database connection URI with embedded credentials',
    recommendation: 'Use environment variables and a connection string without inline credentials',
    cwe: 'CWE-798',
  },
  {
    id: 'MEDUSA-SECRET-JWT',
    name: 'JSON Web Token',
    kind: 'jwt',
    severity: 'medium',
    languages: ['all'],
    pattern: /\beyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g,
    message: 'JWT token detected — may contain sensitive claims',
    recommendation: 'Ensure JWTs are not logged or committed; use short expiry',
  },
  {
    id: 'MEDUSA-SECRET-GOOGLE-API',
    name: 'Google API key',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\bAIza[0-9A-Za-z_-]{35}\b/g,
    message: 'Google API key detected',
    recommendation: 'Restrict the key in Google Cloud Console and rotate if needed',
  },
  {
    id: 'MEDUSA-SECRET-TELEGRAM-BOT',
    name: 'Telegram bot token',
    kind: 'api-key',
    severity: 'high',
    languages: ['all'],
    pattern: /\b\d{8,10}:[A-Za-z0-9_-]{35}\b/g,
    message: 'Telegram Bot API token detected',
    recommendation: 'Revoke via @BotFather on Telegram',
  },
  {
    id: 'MEDUSA-SECRET-SHOPIFY',
    name: 'Shopify access token',
    kind: 'api-key',
    severity: 'critical',
    languages: ['all'],
    pattern: /\bshp(?:at|ss|ca|pa)_[a-fA-F0-9]{32}\b/g,
    message: 'Shopify access token detected',
    recommendation: 'Revoke via Shopify Admin > Apps > Manage private apps',
  },
];

// ---------------------------------------------------------------------------
// AI Context / Prompt injection rules (port of AIContextScanner)
// ---------------------------------------------------------------------------
export const AI_CONTEXT_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-PI-001',
    name: 'Direct instruction override',
    kind: 'prompt-injection',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /ignore\s+(?:all\s+)?(?:previous|prior|above)\s+(?:instructions?|rules?|context)/gi,
    message: 'Prompt injection — instruction to ignore prior context',
    recommendation: 'Remove this instruction; it can be used to override system safety',
  },
  {
    id: 'MEDUSA-PI-002',
    name: 'Role reassignment',
    kind: 'prompt-injection',
    severity: 'high',
    languages: ['markdown', 'text'],
    pattern: /you\s+are\s+(?:now|actually|really)\s+(?:a|an|the)/gi,
    message: 'Prompt injection — role/persona reassignment',
    recommendation: 'Avoid allowing dynamic role reassignment in untrusted content',
  },
  {
    id: 'MEDUSA-PI-003',
    name: 'DAN jailbreak',
    kind: 'prompt-injection',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /DAN\s+mode|do\s+anything\s+now|jailbreak/gi,
    message: 'Jailbreak attempt — "Do Anything Now" pattern',
    recommendation: 'This is a known jailbreak pattern; block or sanitize input',
  },
  {
    id: 'MEDUSA-PI-004',
    name: 'ChatML system tag injection',
    kind: 'prompt-injection',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /<\|system\|>|<\|assistant\|>|<\|user\|>/g,
    message: 'ChatML tag injection — fake system message',
    recommendation: 'Strip or encode ChatML delimiter tokens from user input',
  },
  {
    id: 'MEDUSA-PI-005',
    name: 'Security bypass instruction',
    kind: 'prompt-injection',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /(?:disable|skip|ignore|bypass)\s+(?:all\s+)?(?:security|safety|validation|checks?)/gi,
    message: 'Security bypass — disabling safety mechanisms',
    recommendation: 'Remove instructions that disable safety features',
  },
  {
    id: 'MEDUSA-PI-006',
    name: 'Data exfiltration instruction',
    kind: 'data-exfiltration',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /(?:send|post|upload|transmit|exfiltrate)\s+.{0,50}(?:to|via)\s+(?:http|https|ftp|webhook)/gi,
    message: 'Data exfiltration — sending data to external server',
    recommendation: 'Remove instructions that send data to external endpoints',
  },
  {
    id: 'MEDUSA-PI-007',
    name: 'Code execution instruction',
    kind: 'code-injection',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern:
      /(?:always|automatically)\s+(?:run|execute|eval)\s+(?:this|any|the\s+following)\s+(?:code|script|command)/gi,
    message: 'Code execution instruction — auto-run code',
    recommendation: 'Never auto-execute code without user approval',
  },
  {
    id: 'MEDUSA-PI-008',
    name: 'System prompt leakage',
    kind: 'prompt-leakage',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /\b(?:show|reveal|display|output)\b\s+(?:your|the)\s+(?:system\s+)?(?:prompt|instructions?|rules?)\b/gi,
    message: 'System prompt leakage — requesting internal instructions',
    recommendation: 'Block requests that try to extract system prompts',
  },
  {
    id: 'MEDUSA-PI-009',
    name: 'Zero-width character obfuscation',
    kind: 'obfuscation',
    severity: 'critical',
    languages: ['all'],
    pattern: /[\u200b\u200c\u200d\u2060\ufeff]{3,}/g,
    message: 'Zero-width Unicode characters — possible instruction obfuscation',
    recommendation: 'Strip zero-width characters from input',
  },
  {
    id: 'MEDUSA-PI-010',
    name: 'Hidden instruction in HTML comment',
    kind: 'hidden-instruction',
    severity: 'high',
    languages: ['html', 'markdown'],
    pattern: /<!--\s*(?:IMPORTANT|SECRET|HIDDEN|INTERNAL):/g,
    message: 'Marked HTML comment — possible hidden instruction',
    recommendation: 'Review and remove if used for prompt injection',
  },
  {
    id: 'MEDUSA-PI-011',
    name: 'Sensitive path access',
    kind: 'data-exfiltration',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /(?:read|access|open|cat|get)\s+.{0,50}(?:~\/|\/home\/|\/root\/|\/etc\/|~\/\.ssh|~\/\.aws|~\/\.config)/gi,
    message: 'Instruction to read sensitive file system paths',
    recommendation: 'Block instructions that access sensitive file paths',
  },
  {
    id: 'MEDUSA-PI-012',
    name: 'System tag injection (Llama)',
    kind: 'prompt-injection',
    severity: 'high',
    languages: ['markdown', 'text'],
    pattern: /<<SYS>>|<<\/SYS>>/g,
    message: 'Llama system tag injection',
    recommendation: 'Strip system delimiter tokens from untrusted content',
  },
  {
    id: 'MEDUSA-PI-013',
    name: 'Tool shadowing instruction',
    kind: 'tool-shadowing',
    severity: 'critical',
    languages: ['markdown', 'text'],
    pattern: /(?:override|replace|shadow|intercept)\s+(?:the\s+)?(?:default|existing|built-?in)\s+tool/gi,
    message: 'Tool shadowing — overriding existing tool behavior',
    recommendation: 'Do not allow untrusted configs to shadow tools',
  },
  {
    id: 'MEDUSA-PI-014',
    name: 'Shell access instruction',
    kind: 'command-injection',
    severity: 'high',
    languages: ['markdown', 'text'],
    pattern: /(?:shell|bash|cmd|powershell|terminal)\s+(?:access|commands?)\s+(?:enabled|allowed|permitted)/gi,
    message: 'Instruction enabling shell access',
    recommendation: 'Restrict shell access to approved operations only',
  },
];

// ---------------------------------------------------------------------------
// Universal / generic patterns
// ---------------------------------------------------------------------------
export const UNIVERSAL_RULES: ScannerRule[] = [
  {
    id: 'MEDUSA-UNV-001',
    name: 'TODO / FIXME / HACK / XXX',
    kind: 'code-quality',
    severity: 'info',
    languages: ['all'],
    pattern: /\b(?:TODO|FIXME|HACK|XXX|TEMP|WORKAROUND)\b/g,
    message: 'Code quality marker — unfinished work or workaround',
    recommendation: 'Address before shipping to production',
  },
  {
    id: 'MEDUSA-UNV-002',
    name: 'Hardcoded IP address',
    kind: 'hardcoded',
    severity: 'low',
    languages: ['all'],
    pattern: /\b(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\b/g,
    message: 'Hardcoded IP address — may become stale or leak internal infrastructure',
    recommendation: 'Use environment variables or a config file for IPs',
  },
  {
    id: 'MEDUSA-UNV-003',
    name: 'Large comment block',
    kind: 'code-quality',
    severity: 'info',
    languages: ['all'],
    pattern: /\/\*[\s\S]{500,}\*\//g,
    message: 'Large block comment — may contain outdated or misleading information',
    recommendation: 'Remove commented-out code and stale documentation',
  },
];

// Combine all rules
export const ALL_RULES: ScannerRule[] = [
  ...PYTHON_RULES,
  ...JAVASCRIPT_RULES,
  ...GO_RULES,
  ...RUST_RULES,
  ...PHP_RULES,
  ...IAC_RULES,
  ...SECRET_RULES,
  ...AI_CONTEXT_RULES,
  ...UNIVERSAL_RULES,
];

// ---------------------------------------------------------------------------
// Language detection
// ---------------------------------------------------------------------------
export interface LanguageInfo {
  name: string;
  extensions: string[];
  rules: ScannerRule[];
}

export const LANGUAGE_RULES: Record<string, ScannerRule[]> = {
  python: PYTHON_RULES,
  javascript: JAVASCRIPT_RULES,
  typescript: JAVASCRIPT_RULES,
  go: GO_RULES,
  rust: RUST_RULES,
  php: PHP_RULES,
  terraform: IAC_RULES,
  kubernetes: IAC_RULES,
  dockerfile: IAC_RULES,
  markdown: AI_CONTEXT_RULES,
  text: AI_CONTEXT_RULES,
};

export function detectLanguage(filename: string, content: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  const firstLine = content.split('\n')[0]?.trim() || '';

  const extMap: Record<string, string> = {
    py: 'python',
    js: 'javascript',
    jsx: 'javascript',
    ts: 'typescript',
    tsx: 'typescript',
    go: 'go',
    rs: 'rust',
    php: 'php',
    tf: 'terraform',
    yaml: 'kubernetes',
    yml: 'kubernetes',
    dockerfile: 'dockerfile',
    md: 'markdown',
    dockerignore: 'dockerfile',
  };

  if (extMap[ext]) return extMap[ext];
  if (firstLine.match(/^#!/)) {
    if (/python/i.test(firstLine)) return 'python';
    if (/node/i.test(firstLine)) return 'javascript';
    if (/bash|sh/i.test(firstLine)) return 'text';
  }
  if (/Dockerfile/i.test(filename)) return 'dockerfile';

  return 'text';
}
