/**
 * Threat Monitor — Alert utilities.
 * Browser Notification API + webhook + mailto draft for high-confidence detections.
 */
export interface AlertSettings {
  enabled: boolean;
  /** Minimum confidence (0-1) to trigger an alert */
  threshold: number;
  /** Webhook URL (Slack, Discord, custom) */
  webhookUrl: string;
  /** Email address for mailto: alerts */
  email: string;
  /** Whether browser desktop notifications are enabled */
  browserNotifications: boolean;
  /** Auto-scan interval in minutes (0 = manual only) */
  autoScanMinutes: number;
}

const SETTINGS_KEY = 'tam_alert_settings';

export function loadAlertSettings(): AlertSettings {
  try {
    const raw = localStorage.getItem(SETTINGS_KEY);
    if (raw) return { ...DEFAULT_SETTINGS, ...JSON.parse(raw) };
  } catch {
    /* ignore */
  }
  return { ...DEFAULT_SETTINGS };
}

export function saveAlertSettings(s: AlertSettings) {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(s));
}

export const DEFAULT_SETTINGS: AlertSettings = {
  enabled: false,
  threshold: 0.6,
  webhookUrl: '',
  email: '',
  browserNotifications: false,
  autoScanMinutes: 0,
};

/** Request browser notification permission */
export async function requestNotificationPermission(): Promise<boolean> {
  if (!('Notification' in window)) return false;
  if (Notification.permission === 'granted') return true;
  if (Notification.permission === 'denied') return false;
  const result = await Notification.requestPermission();
  return result === 'granted';
}

/** Send browser desktop notification */
export function sendBrowserNotification(title: string, body: string, url?: string) {
  if (Notification.permission !== 'granted') return;
  const n = new Notification(title, { body, icon: '/favicon.ico', tag: 'tam-alert' });
  if (url)
    n.onclick = () => {
      window.open(url, '_blank');
      n.close();
    };
  setTimeout(() => n.close(), 10000);
}

/** POST to webhook (Slack, Discord, or generic) */
export async function sendWebhook(
  webhookUrl: string,
  detections: { title: string; url: string; confidence: number; apt_groups: string[] }[]
) {
  if (!webhookUrl) return;
  const lines = detections.map(
    (d) =>
      `• **${d.title}** (${(d.confidence * 100).toFixed(0)}% conf)${d.apt_groups.length ? ` — ${d.apt_groups.join(', ')}` : ''}\n  ${d.url}`
  );
  const body = {
    text: `🚨 *TAM Alert: ${detections.length} high-confidence detection(s)*\n\n${lines.join('\n')}`,
    content: `🚨 TAM Alert: ${detections.length} high-confidence detection(s)\n\n${detections.map((d) => `• ${d.title} (${(d.confidence * 100).toFixed(0)}%) ${d.url}`).join('\n')}`,
  };
  try {
    await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(10000),
    });
  } catch {
    /* fire-and-forget */
  }
}

/** Generate mailto: link for email alerts */
export function openEmailAlert(
  settings: AlertSettings,
  detections: { title: string; url: string; confidence: number; apt_groups: string[] }[]
) {
  const subject = encodeURIComponent(`[TAM] ${detections.length} high-confidence threat detection(s)`);
  const body = encodeURIComponent(
    `Global Threat Actor Monitor — High Confidence Alerts\n${'='.repeat(50)}\n\n` +
      detections
        .map(
          (d) =>
            `• ${d.title}\n  Confidence: ${(d.confidence * 100).toFixed(0)}%\n  APT Groups: ${d.apt_groups.join(', ') || 'None'}\n  Link: ${d.url}\n`
        )
        .join('\n') +
      `\n---\nGenerated by Global Threat Actor Monitor`
  );
  window.open(`mailto:${settings.email}?subject=${subject}&body=${body}`, '_blank');
}

/** Process new detections and fire alerts as needed */
export function processAlerts(
  settings: AlertSettings,
  newDetections: { title: string; url: string; confidence: number; apt_groups: string[] }[],
  toast: (msg: string, type?: string) => void
) {
  if (!settings.enabled || newDetections.length === 0) return;

  const alerted = newDetections.filter((d) => d.confidence >= settings.threshold);
  if (alerted.length === 0) return;

  toast(`${alerted.length} high-confidence alert(s) triggered!`, 'warning');

  // Browser notifications (one per detection, max 5)
  if (settings.browserNotifications) {
    alerted.slice(0, 5).forEach((d) => {
      sendBrowserNotification(
        `🚨 ${d.apt_groups[0] ?? 'Threat'} Detected`,
        `${d.title} (${(d.confidence * 100).toFixed(0)}% confidence)`,
        d.url
      );
    });
  }

  // Webhook
  if (settings.webhookUrl) {
    sendWebhook(settings.webhookUrl, alerted);
    toast('Webhook alert sent', 'info');
  }

  // Email draft
  if (settings.email) {
    openEmailAlert(settings, alerted);
    toast('Email draft opened', 'info');
  }
}
