/**
 * FlowViz manifest loader — edge-native read path for the technique index.
 *
 * Data: public/data/flowviz/techniques.json (generated by
 * scripts/build-flowviz-techniques.mjs from the pinned MITRE ATT&CK
 * enterprise STIX bundle; seeded from the FlowViz upstream snapshot).
 *
 * Pattern mirrors worker/lib/si-manifest.ts: slim data ships as a static
 * asset, read at runtime through env.ASSETS, memoised per isolate.
 * No D1, no KV, no upstream fetch on the read path.
 *
 * Attribution: technique names/tactics are MITRE ATT&CK®
 * (© The MITRE Corporation, reproduced with permission — see
 * https://attack.mitre.org/resources/legal-and-branding/terms-of-use/).
 * FlowViz graph schema (MIT) © David L. Johnson.
 */

export interface FlowvizTechniqueTactic {
  id: string;
  name: string;
}

export interface FlowvizTechnique {
  id: string;
  name: string;
  tactics: FlowvizTechniqueTactic[];
}

export interface FlowvizIndexStats {
  source: string;
  sourceUrl: string;
  license: string;
  techniqueCount: number;
  generatedAt?: string;
}

type AssetsFetcher = { fetch: typeof fetch };

let cachedTechniques: FlowvizTechnique[] | null = null;
let pending: Promise<FlowvizTechnique[]> | null = null;

async function fetchJson<T>(assets: AssetsFetcher, path: string): Promise<T> {
  const res = await assets.fetch(new Request(`https://flowviz.local${path}`));
  if (!res.ok) throw new Error(`flowviz asset missing: ${path} (${res.status})`);
  return (await res.json()) as T;
}

export async function loadFlowvizTechniques(assets: AssetsFetcher): Promise<FlowvizTechnique[]> {
  if (cachedTechniques) return cachedTechniques;
  if (!pending) {
    pending = fetchJson<FlowvizTechnique[]>(assets, '/data/flowviz/techniques.json')
      .then((list) => {
        cachedTechniques = Array.isArray(list) ? list : [];
        return cachedTechniques;
      })
      .catch((err) => {
        pending = null;
        throw err;
      });
  }
  return pending;
}

export interface FlowvizTechniqueFilter {
  q?: string;
  tactic?: string;
  limit?: number;
}

/** Prefix-ranked search (mirrors FlowViz attackTechniques.ts ranking). Pure. */
export function filterFlowvizTechniques(
  all: FlowvizTechnique[],
  filter: FlowvizTechniqueFilter = {}
): FlowvizTechnique[] {
  const q = (filter.q ?? '').trim().toLowerCase();
  const tactic = (filter.tactic ?? '').trim().toUpperCase();
  const limit = Math.min(Math.max(filter.limit ?? 50, 1), 200);
  let out = all;
  if (tactic) {
    out = out.filter((t) => t.tactics.some((x) => x.id.toUpperCase() === tactic));
  }
  if (q) {
    const starts: FlowvizTechnique[] = [];
    const contains: FlowvizTechnique[] = [];
    for (const t of out) {
      const hay = `${t.id} ${t.name}`.toLowerCase();
      if (t.id.toLowerCase().startsWith(q) || t.name.toLowerCase().startsWith(q)) starts.push(t);
      else if (hay.includes(q)) contains.push(t);
    }
    out = [...starts, ...contains];
  }
  return out.slice(0, limit);
}

/** Test hook — clears the memoised index. */
export function _resetFlowvizForTests(): void {
  cachedTechniques = null;
  pending = null;
}
