import { Context } from 'hono';
import type { Env } from '../env';
import { LIVE_IOCS_CACHE_KEY, fetchLiveIocs, type LiveIocsResponse } from './live-iocs';

let sidCounter = 2000000;

function nextSid(): number {
  return sidCounter++;
}

async function getIps(ctx: Context<{ Bindings: Env }>): Promise<string[]> {
  const cache = caches.default;
  const cached = await cache.match(new Request(LIVE_IOCS_CACHE_KEY));
  let data: LiveIocsResponse | null = null;
  if (cached) {
    try { data = (await cached.json()) as LiveIocsResponse; } catch { /* ignore */ }
  }
  if (!data) {
    try {
      data = await fetchLiveIocs(ctx.executionCtx, ctx.env.KV_CACHE, ctx.env as never);
    } catch { return []; }
  }
  const ips = data.items.filter((i) => i.kind === 'ip').map((i) => i.value);
  return [...new Set(ips)].sort();
}

function cacheHeaders(): Record<string, string> {
  return {
    'content-type': 'text/plain; charset=utf-8',
    'Cache-Control': 'public, max-age=300',
  };
}

export async function blocklistPfSenseHandler(ctx: Context<{ Bindings: Env }>): Promise<Response> {
  const ips = await getIps(ctx);
  if (ips.length === 0) return new Response('# No IPs available', { status: 200, headers: cacheHeaders() });
  return new Response(ips.join('\n') + '\n', { status: 200, headers: cacheHeaders() });
}

export async function blocklistIptablesHandler(ctx: Context<{ Bindings: Env }>): Promise<Response> {
  const ips = await getIps(ctx);
  if (ips.length === 0) return new Response('#!/bin/sh\n# No IPs available\n', { status: 200, headers: cacheHeaders() });
  const lines = ['#!/bin/sh', '# Generated by pranithjain.qzz.io', '# iptables blocklist — apply with: iptables-restore < this-file'];
  for (const ip of ips) {
    lines.push(`-A INPUT -s ${ip} -j DROP`);
    lines.push(`-A FORWARD -s ${ip} -j DROP`);
  }
  return new Response(lines.join('\n') + '\n', { status: 200, headers: cacheHeaders() });
}

export async function blocklistSuricataHandler(ctx: Context<{ Bindings: Env }>): Promise<Response> {
  const ips = await getIps(ctx);
  if (ips.length === 0) {
    return new Response('# No Suricata rules generated — no IPs available\n', { status: 200, headers: cacheHeaders() });
  }
  const ts = new Date().toISOString().slice(0, 10);
  const header = [
    `# Suricata drop rules — generated ${ts} by pranithjain.qzz.io`,
    `# ${ips.length} IPs from live threat intelligence feeds`,
    '',
  ];
  const rules = ips.map((ip) => {
    const sid = nextSid();
    return `drop ip ${ip} any -> any any (msg:"BLOCKLIST malicious IP ${ip}"; classtype:trojan-activity; sid:${sid}; rev:1;)`;
  });
  return new Response([...header, ...rules].join('\n') + '\n', { status: 200, headers: cacheHeaders() });
}
