import { useEffect, useMemo, useState } from 'react';
import { sanitizeUrl } from '../../lib/sanitize-url';
import { useParams } from 'react-router-dom';
import {
  ExternalLink,
  AlertTriangle,
  ShieldAlert,
  TrendingUp,
  Users,
  ListChecks,
  Compass,
  Sparkles,
  Download,
  Copy,
  Check,
} from 'lucide-react';
import { IntelCard } from '../../components/intel/IntelCard';
import { AutoGeneratedBadge } from '../../components/AutoGeneratedBadge';
import { BackLink } from '../../components/BackLink';
import { SEVERITY_TONE, type Severity as CanonSeverity } from '../../components/severity';

/**
 * Wire-level severity as it can arrive from the briefing API — includes the
 * legacy `'unknown'` bucket that the canonical ramp folds into `low`.
 */
type Severity = 'critical' | 'high' | 'medium' | 'low' | 'unknown';

/** Map a wire severity onto the canonical ramp (unknown → low). */
function canonSeverity(s: Severity): CanonSeverity {
  return s === 'unknown' ? 'low' : s;
}

/** Short uppercase label per (wire) severity for the finding chip. */
const SEVERITY_LABEL: Record<Severity, string> = {
  critical: 'CRIT',
  high: 'HIGH',
  medium: 'MED',
  low: 'LOW',
  unknown: 'N/A',
};

/** Severity-coloured focus ring, aligned to the canonical ramp. */
const SEVERITY_RING: Record<CanonSeverity, string> = {
  critical: 'ring-rose-500/40',
  high: 'ring-orange-500/40',
  medium: 'ring-amber-500/40',
  low: 'ring-slate-400/40',
  info: 'ring-sky-500/40',
};

interface BriefingFinding {
  id: string;
  title: string;
  description: string;
  severity: Severity;
  cvss?: number;
  source: string;
  source_url?: string;
  mitre_techniques: string[];
  added?: string;
  vendor?: string;
  product?: string;
  tags?: {
    cves: string[];
    actors: Array<{ slug: string; mitre_id?: string }>;
    sectors: string[];
  };
}

interface BriefingSection {
  id: string;
  title: string;
  blurb: string;
  count: number;
  findings: BriefingFinding[];
}

interface IocEntry {
  type: string;
  value: string;
  context?: string;
  timestamp?: string;
}

interface BriefingStats {
  findings: number;
  sections: number;
  cves: number;
  kevs: number;
  iocs: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  ransomware_victims: number;
}

interface Briefing {
  slug: string;
  type: 'daily' | 'weekly' | 'landscape';
  title: string;
  date: string;
  date_range: string;
  range_start: string;
  range_end: string;
  generated_at: string;
  executive_summary: string;
  degraded?: boolean;
  stats: BriefingStats;
  sections: BriefingSection[];
  iocs: { urls: IocEntry[]; domains: IocEntry[]; ipv4s: IocEntry[]; hashes: IocEntry[] };
  ioc_dump?: { count: number; rawTotal: number; content: string };
  mitre_techniques: string[];
  sources: string[];
}

/**
 * Shape of a `type === 'landscape'` briefing. Built by
 * api/src/lib/landscape-builder.ts — see that file for the canonical
 * section list. We type-assert from `unknown` when handing off the
 * already-loaded briefing so the rest of the page can stay loose.
 */
interface LandscapeSection {
  id: string;
  title: string;
  blurb: string;
  count: number;
  findings: Array<{
    id: string;
    title: string;
    description: string;
    severity: Severity;
    source: string;
    source_url?: string;
    count?: number;
  }>;
}

interface LandscapeReport {
  slug: string;
  type: 'landscape';
  title: string;
  date: string;
  date_range: string;
  range_start: string;
  range_end: string;
  generated_at: string;
  executive_summary: string;
  top_threats: LandscapeSection;
  trending_actors: LandscapeSection;
  key_incidents: LandscapeSection;
  recommended_actions: LandscapeSection;
  outlook: LandscapeSection;
  stats: {
    ransomware_victims: number;
    top_groups: number;
    incidents_surfaced: number;
    recommendations: number;
    sources: number;
  };
  sources: string[];
}

function StatPill({ label, value, accent }: { label: string; value: number | string; accent?: string }) {
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={`text-2xl font-display font-bold ${accent ?? 'text-slate-900 dark:text-white'}`}>{value}</span>
      <span className="text-micro font-mono uppercase tracking-wider text-slate-500">{label}</span>
    </div>
  );
}

function MitreChip({ technique }: { technique: string }) {
  const href = `https://attack.mitre.org/techniques/${technique.replace('.', '/')}`;
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="text-xs font-mono px-2 py-0.5 rounded bg-slate-100 dark:bg-[rgb(var(--surface-200))] text-brand-600 dark:text-brand-400 border border-slate-200 dark:border-[rgb(var(--border-400))] hover:border-brand-500/40 transition-colors"
    >
      {technique}
    </a>
  );
}

function FindingCard({ finding }: { finding: BriefingFinding }) {
  const canon = canonSeverity(finding.severity);
  return (
    <article className={`surface-card p-5 ring-1 ${SEVERITY_RING[canon]}`}>
      <div className="flex items-start justify-between gap-3 mb-2">
        <h4 className="font-display font-bold text-base text-slate-900 dark:text-white leading-snug">
          {finding.title}
        </h4>
        <span
          className={`text-micro font-mono uppercase tracking-wider px-2 py-0.5 rounded border ${SEVERITY_TONE[canon]} shrink-0`}
        >
          {SEVERITY_LABEL[finding.severity]}
          {finding.cvss !== undefined && ` · ${finding.cvss.toFixed(1)}`}
        </span>
      </div>
      {finding.description && (
        <p className="text-sm text-muted leading-relaxed mb-3 line-clamp-6">{finding.description}</p>
      )}
      {finding.tags &&
        (finding.tags.cves.length > 0 || finding.tags.actors.length > 0 || finding.tags.sectors.length > 0) && (
          <div className="flex flex-wrap gap-1.5 mb-3">
            {finding.tags.cves.map((cve) => (
              <a
                key={`cve-${cve}`}
                href={`https://nvd.nist.gov/vuln/detail/${cve}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-micro font-mono px-1.5 py-0.5 rounded border border-rose-500/40 bg-rose-500/10 text-rose-700 dark:text-rose-300 hover:underline"
                title={`Look up ${cve} on NVD`}
              >
                {cve}
              </a>
            ))}
            {finding.tags.actors.map((a) => (
              <span
                key={`actor-${a.slug}`}
                className="text-micro font-mono px-1.5 py-0.5 rounded border border-violet-500/40 bg-violet-500/10 text-violet-700 dark:text-violet-300"
                title={a.mitre_id ? `MITRE ${a.mitre_id}` : 'actor name detected'}
              >
                actor:{a.slug}
                {a.mitre_id && <span className="opacity-70"> · {a.mitre_id}</span>}
              </span>
            ))}
            {finding.tags.sectors.map((s) => (
              <span
                key={`sector-${s}`}
                className="text-micro font-mono px-1.5 py-0.5 rounded border border-sky-500/40 bg-sky-500/10 text-sky-700 dark:text-sky-300"
                title="heuristic sector classification"
              >
                sector:{s}
              </span>
            ))}
          </div>
        )}
      <div className="flex flex-wrap items-center gap-2 text-mini font-mono text-slate-400">
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-slate-100 dark:bg-[rgb(var(--surface-200))] border border-slate-200 dark:border-[rgb(var(--border-400))]">
          {finding.source}
        </span>
        {finding.added && <span>added {finding.added}</span>}
        {finding.mitre_techniques.length > 0 && (
          <span className="flex flex-wrap gap-1">
            {finding.mitre_techniques.map((t) => (
              <MitreChip key={t} technique={t} />
            ))}
          </span>
        )}
        {finding.source_url && (
          <a
            href={sanitizeUrl(finding.source_url) || undefined}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-brand-600 dark:text-brand-400 hover:underline ml-auto"
          >
            details <ExternalLink size={11} />
          </a>
        )}
      </div>
    </article>
  );
}

/**
 * Render the IOC dump as a single panel: a download button (which fetches the
 * real /api/v1/briefings/:slug/iocs.txt and saves it as `<slug>-iocs.txt`),
 * a copy-to-clipboard button, and a <pre> preview of the inlined content.
 *
 * Why not just <a href download>? Direct anchors get blocked through some
 * browsers when the response has a different origin; fetching and creating
 * a Blob URL is bullet-proof and also lets us show a brief "Copied!" toast.
 */
function IocDumpPanel({
  slug,
  dump,
}: {
  slug: string;
  dump: { count: number; rawTotal: number; content: string };
}): JSX.Element {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const download = async () => {
    if (downloading) return;
    setDownloading(true);
    try {
      const res = await fetch(`/api/v1/briefings/${encodeURIComponent(slug)}/iocs.txt`);
      if (!res.ok) throw new Error(`http ${res.status}`);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${slug}-iocs.txt`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      // Revoke after the click event has fired; small delay is enough.
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (_catchErr) {
      console.error('IocDumpPanel failed:', _catchErr instanceof Error ? _catchErr.message : String(_catchErr));
      // Last-resort: fall back to the inlined content (still a valid txt).
      const blob = new Blob([dump.content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${slug}-iocs.txt`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } finally {
      setDownloading(false);
    }
  };

  const copy = async () => {
    if (copied) return;
    try {
      await navigator.clipboard.writeText(dump.content);
    } catch (_catchErr) {
      console.error('handler failed:', _catchErr instanceof Error ? _catchErr.message : String(_catchErr));
      // Fall back to a hidden textarea + execCommand for older browsers.
      const ta = document.createElement('textarea');
      ta.value = dump.content;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand('copy');
      } catch (err) {
        console.error('handler failed:', err instanceof Error ? err.message : String(err));
        // Older browser / insecure context — clipboard copy unavailable.
        // We just silently fall through; the download button is the other path.
        void err;
      }
      ta.remove();
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };

  return (
    <section className="surface-card p-5">
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={download}
          disabled={downloading}
          className="inline-flex items-center gap-1.5 rounded bg-brand-600 px-3 py-1.5 text-xs font-semibold text-white shadow-e1 transition-colors hover:bg-brand-700 disabled:opacity-60 dark:bg-brand-500 dark:hover:bg-brand-400"
        >
          <Download className="h-3.5 w-3.5" />
          {downloading ? 'Downloading…' : 'Download .txt'}
        </button>
        <button
          type="button"
          onClick={copy}
          className="inline-flex items-center gap-1.5 rounded border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 transition-colors hover:border-brand-400 hover:text-brand-700 dark:border-[rgb(var(--border-400))] dark:bg-[rgb(var(--surface-200))] dark:text-slate-200 dark:hover:border-brand-500 dark:hover:text-brand-300"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? 'Copied' : 'Copy'}
        </button>
        <span className="ml-auto text-mini uppercase tracking-wider text-slate-500">
          blocklist seed · one indicator per line
        </span>
      </div>
      <pre className="max-h-96 overflow-auto rounded-xl bg-slate-50 p-3 font-mono text-xs leading-5 text-slate-800 dark:bg-[rgb(var(--input-200))] dark:text-slate-200">
        {dump.content}
      </pre>
    </section>
  );
}

/**
 * Jump-nav pill row for the daily/weekly briefing detail page. Lets the user
 * jump straight to the CVE findings, ransomware victims, IOC dump, or MITRE
 * techniques block without scrolling through a long page. Pills carry a
 * count badge so a reader can see at a glance "this brief has 0 ransomware
 * victims" without expanding the section.
 *
 * Pills are plain <a href="#anchor"> links so they survive prerender, no-JS
 * viewers, and the keyboard-tab order. Anchor targets are added to the
 * section wrappers (id="briefing-cves", id="briefing-ransomware", etc.).
 */
function JumpNav({
  cveCount,
  ransomwareCount,
  iocCount,
  mitreCount,
}: {
  cveCount: number;
  ransomwareCount: number;
  iocCount: number;
  mitreCount: number;
}): JSX.Element | null {
  // Hide the row entirely if there's literally nothing to jump to (a
  // landscape report, or a daily that has zero of every category).
  if (cveCount + ransomwareCount + iocCount + mitreCount === 0) return null;
  return (
    <nav
      aria-label="Jump to section"
      className="mb-8 flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 dark:border-[rgb(var(--border-400))] bg-white/60 dark:bg-[rgb(var(--surface-200))]/60 px-3 py-2 text-xs"
    >
      <span className="font-display font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mr-1">
        Jump to
      </span>
      {cveCount > 0 && (
        <a
          href="#briefing-cves"
          className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 dark:border-[rgb(var(--border-400))] bg-white dark:bg-[rgb(var(--surface-200))] px-3 py-1 font-semibold text-slate-700 dark:text-slate-200 hover:border-brand-400 hover:text-brand-700 dark:hover:text-brand-300 transition-colors"
        >
          <ShieldAlert className="h-3.5 w-3.5" />
          CVEs
          <span className="rounded-full bg-slate-100 dark:bg-[rgb(var(--surface-200))] px-1.5 text-mini font-mono text-slate-600 dark:text-slate-300">
            {cveCount.toLocaleString()}
          </span>
        </a>
      )}
      {ransomwareCount > 0 && (
        <a
          href="#briefing-ransomware"
          className="inline-flex items-center gap-1.5 rounded-full border border-rose-200 dark:border-rose-900 bg-rose-50 dark:bg-rose-950/30 px-3 py-1 font-semibold text-rose-700 dark:text-rose-300 hover:border-rose-400 transition-colors"
        >
          <Users className="h-3.5 w-3.5" />
          Ransomware
          <span className="rounded-full bg-rose-100 dark:bg-rose-900/50 px-1.5 text-mini font-mono">
            {ransomwareCount.toLocaleString()}
          </span>
        </a>
      )}
      {iocCount > 0 && (
        <a
          href="#briefing-iocs"
          className="inline-flex items-center gap-1.5 rounded-full border border-emerald-200 dark:border-emerald-900 bg-emerald-50 dark:bg-emerald-950/30 px-3 py-1 font-semibold text-emerald-700 dark:text-emerald-300 hover:border-emerald-400 transition-colors"
        >
          <ListChecks className="h-3.5 w-3.5" />
          IOCs
          <span className="rounded-full bg-emerald-100 dark:bg-emerald-900/50 px-1.5 text-mini font-mono">
            {iocCount.toLocaleString()}
          </span>
        </a>
      )}
      {mitreCount > 0 && (
        <a
          href="#briefing-mitre"
          className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 dark:border-[rgb(var(--border-400))] bg-white dark:bg-[rgb(var(--surface-200))] px-3 py-1 font-semibold text-slate-700 dark:text-slate-200 hover:border-brand-400 hover:text-brand-700 dark:hover:text-brand-300 transition-colors"
        >
          <Compass className="h-3.5 w-3.5" />
          MITRE
          <span className="rounded-full bg-slate-100 dark:bg-[rgb(var(--surface-200))] px-1.5 text-mini font-mono text-slate-600 dark:text-slate-300">
            {mitreCount.toLocaleString()}
          </span>
        </a>
      )}
    </nav>
  );
}

/**
 * Landscape-report specific view. Distinct from the daily/weekly view
 * because the data shape is different — landscape reports have named
 * sections (top_threats, trending_actors, key_incidents,
 * recommended_actions, outlook) rather than a generic sections[] array,
 * and they don't carry IOC tables.
 */
function LandscapeReportView({ briefing }: { briefing: LandscapeReport }): JSX.Element {
  const sections: Array<{
    key: keyof LandscapeReport;
    section: LandscapeSection;
    icon: typeof TrendingUp;
    accent: string;
  }> = [
    {
      key: 'top_threats',
      section: briefing.top_threats,
      icon: TrendingUp,
      accent: 'text-amber-600 dark:text-amber-400',
    },
    {
      key: 'trending_actors',
      section: briefing.trending_actors,
      icon: Users,
      accent: 'text-violet-600 dark:text-violet-400',
    },
    {
      key: 'key_incidents',
      section: briefing.key_incidents,
      icon: ListChecks,
      accent: 'text-rose-600 dark:text-rose-400',
    },
    {
      key: 'recommended_actions',
      section: briefing.recommended_actions,
      icon: ShieldAlert,
      accent: 'text-emerald-600 dark:text-emerald-400',
    },
    {
      key: 'outlook',
      section: briefing.outlook,
      icon: Compass,
      accent: 'text-sky-600 dark:text-sky-400',
    },
  ];
  const stats = briefing.stats;
  return (
    <>
      {/* Landscape KPI bar */}
      <section className="surface-card p-4 mb-8">
        <div className="flex flex-wrap items-center justify-around gap-6">
          <StatPill label="victims" value={stats.ransomware_victims} accent="text-rose-600 dark:text-rose-400" />
          <StatPill label="actors" value={stats.top_groups} accent="text-violet-600 dark:text-violet-400" />
          <StatPill label="incidents" value={stats.incidents_surfaced} accent="text-amber-600 dark:text-amber-400" />
          <StatPill label="actions" value={stats.recommendations} accent="text-emerald-600 dark:text-emerald-400" />
          <StatPill label="sources" value={stats.sources} accent="text-sky-600 dark:text-sky-400" />
        </div>
      </section>

      {/* Executive summary */}
      <section className="mb-10">
        <h2 className="font-display font-bold text-lg mb-3 flex items-center gap-2">
          <Sparkles size={18} className="text-brand-600 dark:text-brand-400" /> Executive Summary
        </h2>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{briefing.executive_summary}</p>
      </section>

      {/* Sections */}
      <section className="mb-12 space-y-8">
        {sections.map(({ key, section, icon: Icon, accent }) => (
          <div key={key as string}>
            <div className="flex items-baseline justify-between mb-2">
              <h2 className="font-display font-bold text-xl flex items-center gap-2">
                <Icon size={18} className={accent} />
                {section.title}
              </h2>
              <span className="text-xs font-mono text-slate-500">{section.count} items</span>
            </div>
            <p className="text-sm text-muted mb-4">{section.blurb}</p>
            <div className="space-y-3">
              {section.findings.map((f) => (
                <article key={f.id} className="surface-card p-5">
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <h4 className="font-display font-bold text-base text-slate-900 dark:text-white leading-snug">
                      {f.title}
                    </h4>
                    {f.count !== undefined && (
                      <span className="text-micro font-mono uppercase tracking-wider px-2 py-0.5 rounded border bg-slate-100 dark:bg-[rgb(var(--surface-200))] border-slate-200 dark:border-[rgb(var(--border-400))] text-slate-600 dark:text-slate-300 shrink-0">
                        ×{f.count}
                      </span>
                    )}
                  </div>
                  {f.description && (
                    <p className="text-sm text-muted leading-relaxed mb-3 line-clamp-4">{f.description}</p>
                  )}
                  <div className="flex flex-wrap items-center gap-2 text-mini font-mono text-slate-400">
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-slate-100 dark:bg-[rgb(var(--surface-200))] border border-slate-200 dark:border-[rgb(var(--border-400))]">
                      {f.source}
                    </span>
                    {f.source_url && (
                      <a
                        href={sanitizeUrl(f.source_url) || undefined}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-brand-600 dark:text-brand-400 hover:underline ml-auto"
                      >
                        details <ExternalLink size={11} />
                      </a>
                    )}
                  </div>
                </article>
              ))}
            </div>
          </div>
        ))}
      </section>
    </>
  );
}

export default function BriefingDetail(): JSX.Element {
  const { slug } = useParams<{ slug: string }>();
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshKey, setRefreshKey] = useState(0);

  useEffect(() => {
    if (!slug) return;
    let cancelled = false;
    const ctrl = new AbortController();
    setLoading(true);
    setError(null);
    setBriefing(null);
    fetch(`/api/v1/briefings/${encodeURIComponent(slug)}`, {
      signal: AbortSignal.any([ctrl.signal, AbortSignal.timeout(15_000)]),
    })
      .then(async (r) => {
        if (!r.ok) {
          const body = await r.text().catch(() => '');
          let msg = `${r.status}`;
          try {
            const parsed = JSON.parse(body) as { error?: string };
            msg = parsed.error ?? msg;
          } catch (_catchErr) {
            console.error('BriefingDetail failed:', _catchErr instanceof Error ? _catchErr.message : String(_catchErr));
            /* use default */
          }
          throw new Error(msg);
        }
        const ct = r.headers.get('content-type') ?? '';
        if (!ct.includes('json')) throw new Error('Server returned non-JSON response');
        return (await r.json()) as Briefing;
      })
      .then((b) => {
        if (!cancelled) setBriefing(b);
      })
      .catch((err: { name?: string; message?: string }) => {
        if (cancelled || err.name === 'AbortError') return;
        setError(err.message ?? 'failed to load');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
      ctrl.abort();
    };
  }, [slug, refreshKey]);

  // Concatenate the briefing's narrative content into one body string the
  // intel extractor can scan — executive summary + every finding's title +
  // description. The flat-IoC tables further down stay as the human-friendly
  // browsing surface; the card adds the structured STIX 2.1 view on top.
  // Called before the conditional returns so it satisfies the rules-of-hooks
  // ordering invariant across renders.
  const intelBody = useMemo(() => {
    if (!briefing) return '';
    const parts: string[] = [briefing.executive_summary];
    // Landscape reports have a different structure — use named sections.
    if (briefing.type === 'landscape') {
      const lr = briefing as unknown as LandscapeReport;
      for (const section of [
        lr.top_threats,
        lr.trending_actors,
        lr.key_incidents,
        lr.recommended_actions,
        lr.outlook,
      ]) {
        parts.push(`\n\n## ${section.title}\n${section.blurb}`);
        for (const f of section.findings) {
          parts.push(`\n### ${f.title}\n${f.description}`);
        }
      }
    } else {
      for (const s of briefing.sections) {
        parts.push(`\n\n## ${s.title}\n${s.blurb}`);
        for (const f of s.findings) {
          parts.push(`\n### ${f.title}\n${f.description}`);
        }
      }
    }
    return parts.join('\n');
  }, [briefing]);

  if (loading) {
    return (
      <div className="max-w-5xl mx-auto px-4 sm:px-8 py-12 sm:py-16 font-mono text-sm text-slate-500">
        Loading briefing…
      </div>
    );
  }
  if (error || !briefing) {
    return (
      <div className="max-w-5xl mx-auto px-4 sm:px-8 py-12 sm:py-16">
        <BackLink to="/threatintel">back</BackLink>
        <h1 className="font-display font-bold text-2xl text-slate-900 dark:text-white mb-2">Briefing not found</h1>
        <p className="text-sm text-slate-500">
          {error ??
            'This briefing has not been generated yet. Daily briefings publish at 00:05 UTC; weekly at 00:15 UTC Monday.'}
        </p>
        <button
          type="button"
          onClick={() => setRefreshKey((k) => k + 1)}
          className="mt-4 inline-flex items-center gap-1 text-meta font-mono px-2.5 py-1.5 rounded border border-slate-300 dark:border-[rgb(var(--border-400))] hover:border-brand-500/40"
        >
          retry
        </button>
      </div>
    );
  }

  const stats = briefing.stats;
  const shareUrl = typeof window !== 'undefined' ? window.location.href : '';
  const shareTitle = briefing.title;
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-8 py-12 text-slate-900 dark:text-white">
      <BackLink to="/threatintel">back</BackLink>

      <header className="animate-fade-in-up mb-8">
        <span className="inline-block text-eyebrow font-mono uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400 mb-3">
          Intel Briefing · {briefing.type}
        </span>
        <h1 className="text-3xl sm:text-4xl font-display font-bold leading-tight mb-2">{briefing.title}</h1>
        <p className="text-sm font-mono text-slate-500 mb-3">
          {briefing.date_range} · generated {briefing.generated_at.slice(0, 16).replace('T', ' ')} UTC
        </p>
        <AutoGeneratedBadge kind="briefing" generatedAt={briefing.generated_at} variant="banner" />
        {briefing.degraded && (
          <div
            role="alert"
            className="mt-4 rounded-xl border border-amber-300 dark:border-amber-800/60 bg-amber-50 dark:bg-amber-900/15 p-4"
          >
            <div className="flex items-start gap-3">
              <AlertTriangle
                size={18}
                className="text-amber-700 dark:text-amber-400 shrink-0 mt-0.5"
                aria-hidden="true"
              />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-semibold text-amber-900 dark:text-amber-200">
                  Upstream feeds were unreachable when this briefing was built.
                </p>
                <p className="text-xs text-amber-800 dark:text-amber-300 mt-1 leading-relaxed">
                  CISA KEV and NVD returned errors from the edge at build time. The hourly self-heal will rebuild this
                  briefing as soon as the feeds respond — within an hour of recovery. This is{' '}
                  <span className="font-semibold">not</span> an all-clear; do not treat zero findings as &quot;no new
                  vulnerabilities&quot;.
                </p>
                <button
                  type="button"
                  onClick={() => setRefreshKey((k) => k + 1)}
                  className="mt-3 inline-flex items-center gap-1.5 text-xs font-mono px-2.5 py-1.5 rounded border border-amber-400/60 text-amber-900 dark:text-amber-200 hover:bg-amber-500/10"
                >
                  retry now
                </button>
              </div>
            </div>
          </div>
        )}
        <a
          href={`/api/v1/briefings/${briefing.slug}/print`}
          target="_blank"
          className="mt-3 inline-flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-xl border border-slate-300 dark:border-[rgb(var(--border-400))] hover:border-brand-500/40 hover:bg-brand-500/5 transition-colors"
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          Print / PDF
        </a>
        <div className="mt-3 flex items-center gap-2">
          <a
            href={`https://x.com/intent/tweet?text=${encodeURIComponent(shareTitle)}&url=${encodeURIComponent(shareUrl)}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-xl border border-slate-300 dark:border-[rgb(var(--border-400))] hover:border-brand-500/40 hover:bg-brand-500/5 transition-colors"
          >
            <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
            X
          </a>
          <a
            href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-xl border border-slate-300 dark:border-[rgb(var(--border-400))] hover:border-brand-500/40 hover:bg-brand-500/5 transition-colors"
          >
            <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
            </svg>
            LinkedIn
          </a>
        </div>
      </header>

      {/* Landscape reports have their own section layout — branch before the
          daily/weekly findings/IOC tables render. */}
      {briefing.type === 'landscape' && <LandscapeReportView briefing={briefing as unknown as LandscapeReport} />}

      {/* Stats bar — daily/weekly only; landscape has its own stats in LandscapeReportView. */}
      {briefing.type !== 'landscape' && (
        <section className="surface-card p-4 mb-8">
          <div className="flex flex-wrap items-center justify-around gap-6">
            <StatPill label="findings" value={stats.findings} />
            <StatPill label="sections" value={stats.sections} />
            <StatPill label="CVEs" value={stats.cves} />
            <StatPill label="KEVs" value={stats.kevs} />
            <StatPill label="IOCs" value={stats.iocs} />
            <StatPill label="critical" value={stats.critical} accent="text-rose-600 dark:text-rose-400" />
            <StatPill label="high" value={stats.high} accent="text-orange-600 dark:text-orange-400" />
            <StatPill label="medium" value={stats.medium} accent="text-amber-600 dark:text-amber-400" />
            <StatPill label="low" value={stats.low} accent="text-slate-600 dark:text-slate-300" />
          </div>
        </section>
      )}

      {/* Jump-nav pills — link to the CVE / ransomware / IOC / MITRE blocks
          further down the page. Hidden on landscape reports and on briefs
          that have nothing in any of those buckets. */}
      {briefing.type !== 'landscape' && (
        <JumpNav
          cveCount={stats.cves}
          ransomwareCount={stats.ransomware_victims}
          iocCount={stats.iocs}
          mitreCount={briefing.mitre_techniques?.length ?? 0}
        />
      )}

      {/* Structured STIX 2.1 intel view. Renders an enriched card backed by
          /api/v1/intel-bundle — heuristic-extracted actors, malware, CVEs,
          theme tags + bulk-enriched IoCs with risk scores. Falls back to
          rendering nothing while loading so the Executive Summary still
          carries the page on first paint. */}
      <section className="mb-10">
        <IntelCard
          sourceId="briefings"
          itemRef={briefing.slug}
          item={{
            title: briefing.title,
            body: intelBody,
            publishedAt: briefing.generated_at,
          }}
          fallback={null}
        />
      </section>

      {/* Executive Summary */}
      <section className="mb-10">
        <h2 className="font-display font-bold text-lg mb-3 flex items-center gap-2">
          <ShieldAlert size={18} className="text-brand-600 dark:text-brand-400" /> Executive Summary
        </h2>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{briefing.executive_summary}</p>
      </section>

      {/* Sections — daily/weekly only; landscape uses LandscapeReportView above.
          The id="briefing-cves" target is used by the JumpNav pills. */}
      {briefing.type !== 'landscape' && briefing.sections && briefing.sections.length > 0 && (
        <section id="briefing-cves" className="mb-12 space-y-8 scroll-mt-20">
          {briefing.sections.map((s) => (
            <div
              key={s.id}
              id={s.id === 'ransomware-activity' ? 'briefing-ransomware' : undefined}
              className="scroll-mt-20"
            >
              <div className="flex items-baseline justify-between mb-2">
                <h2 className="font-display font-bold text-xl flex items-center gap-2">
                  <AlertTriangle size={18} className="text-brand-600 dark:text-brand-400" />
                  {s.title}
                </h2>
                <span className="text-xs font-mono text-slate-500">
                  {s.count} {s.count === 1 ? 'finding' : 'findings'}
                </span>
              </div>
              <p className="text-sm text-muted mb-4">{s.blurb}</p>
              <div className="space-y-3">
                {s.findings.map((f) => (
                  <FindingCard key={f.id} finding={f} />
                ))}
              </div>
            </div>
          ))}
        </section>
      )}

      {/* No sections message — when there are no findings but IOCs exist */}
      {briefing.type !== 'landscape' &&
        briefing.sections.length === 0 &&
        briefing.ioc_dump &&
        briefing.ioc_dump.count > 0 && (
          <section className="mb-8 surface-card p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle size={18} className="text-amber-500 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-slate-900 dark:text-white mb-1">
                  No new critical/high CVEs in this period
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                  The upstream feeds (CISA KEV, NVD) had no new high/critical vulnerabilities for this date range. The
                  IOC indicators below were still collected from URLhaus, MalwareBazaar, ThreatFox, and TweetFeed.
                </p>
              </div>
            </div>
          </section>
        )}

      {/* MITRE techniques observed — daily/weekly only. id="briefing-mitre" is
          the JumpNav target. */}
      {briefing.type !== 'landscape' && briefing.mitre_techniques && briefing.mitre_techniques.length > 0 && (
        <section id="briefing-mitre" className="mb-10 scroll-mt-20">
          <h2 className="font-display font-bold text-lg mb-3">MITRE ATT&amp;CK Techniques Observed</h2>
          <div className="flex flex-wrap gap-2">
            {briefing.mitre_techniques.map((t) => (
              <MitreChip key={t} technique={t} />
            ))}
          </div>
        </section>
      )}

      {/* IOCs — daily/weekly only. Rendered as a single txt dump (capped at
          30 total) with download + copy buttons, NOT inline tables. The inline
          per-kind IocTable is gone — when a user wants the actual list of
          indicators they grab the txt and use it as a blocklist seed.
          id="briefing-iocs" is the JumpNav target. */}
      {briefing.type !== 'landscape' && briefing.ioc_dump && briefing.ioc_dump.count > 0 && (
        <section id="briefing-iocs" className="mb-10 scroll-mt-20">
          <div className="mb-4 flex items-baseline justify-between gap-4">
            <h2 className="font-display font-bold text-lg">Active Threat Indicators</h2>
            <span className="text-xs font-mono text-slate-500">
              {briefing.ioc_dump.count.toLocaleString()} unique indicators
            </span>
          </div>
          <IocDumpPanel slug={briefing.slug} dump={briefing.ioc_dump} />
        </section>
      )}

      {/* Footer */}
      <footer className="mt-12 pt-6 border-t border-slate-200 dark:border-[rgb(var(--border-400))] text-xs font-mono text-slate-500">
        <p>
          Sources: {briefing.sources.join(', ') || 'none'}. Reference only. Verify all indicators in your own
          environment. Generated {briefing.generated_at.slice(0, 16).replace('T', ' ')} UTC.
        </p>
      </footer>
    </div>
  );
}
