import { useEffect, useMemo, useState } from 'react';
import { sanitizeUrl } from '../../lib/sanitize-url';
import { Link, useParams } from 'react-router-dom';
import {
  ArrowLeft,
  ExternalLink,
  AlertTriangle,
  ShieldAlert,
  TrendingUp,
  Users,
  ListChecks,
  Compass,
  Sparkles,
} from 'lucide-react';
import { IntelCard } from '../../components/intel/IntelCard';
import { AutoGeneratedBadge } from '../../components/AutoGeneratedBadge';
import { SEVERITY_TONE, type Severity as CanonSeverity } from '../../components/severity';

/**
 * Wire-level severity as it can arrive from the briefing API — includes the
 * legacy `'unknown'` bucket that the canonical ramp folds into `low`.
 */
type Severity = 'critical' | 'high' | 'medium' | 'low' | 'unknown';

/** Map a wire severity onto the canonical ramp (unknown → low). */
function canonSeverity(s: Severity): CanonSeverity {
  return s === 'unknown' ? 'low' : s;
}

/** Short uppercase label per (wire) severity for the finding chip. */
const SEVERITY_LABEL: Record<Severity, string> = {
  critical: 'CRIT',
  high: 'HIGH',
  medium: 'MED',
  low: 'LOW',
  unknown: 'N/A',
};

/** Severity-coloured focus ring, aligned to the canonical ramp. */
const SEVERITY_RING: Record<CanonSeverity, string> = {
  critical: 'ring-rose-500/40',
  high: 'ring-orange-500/40',
  medium: 'ring-amber-500/40',
  low: 'ring-slate-400/40',
  info: 'ring-sky-500/40',
};

interface BriefingFinding {
  id: string;
  title: string;
  description: string;
  severity: Severity;
  cvss?: number;
  source: string;
  source_url?: string;
  mitre_techniques: string[];
  added?: string;
  vendor?: string;
  product?: string;
  tags?: {
    cves: string[];
    actors: Array<{ slug: string; mitre_id?: string }>;
    sectors: string[];
  };
}

interface BriefingSection {
  id: string;
  title: string;
  blurb: string;
  count: number;
  findings: BriefingFinding[];
}

interface IocEntry {
  type: string;
  value: string;
  context?: string;
  timestamp?: string;
}

interface BriefingStats {
  findings: number;
  sections: number;
  cves: number;
  kevs: number;
  iocs: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
}

interface Briefing {
  slug: string;
  type: 'daily' | 'weekly' | 'landscape';
  title: string;
  date: string;
  date_range: string;
  range_start: string;
  range_end: string;
  generated_at: string;
  executive_summary: string;
  degraded?: boolean;
  stats: BriefingStats;
  sections: BriefingSection[];
  iocs: { urls: IocEntry[]; domains: IocEntry[]; ipv4s: IocEntry[]; hashes: IocEntry[] };
  mitre_techniques: string[];
  sources: string[];
}

/**
 * Shape of a `type === 'landscape'` briefing. Built by
 * api/src/lib/landscape-builder.ts — see that file for the canonical
 * section list. We type-assert from `unknown` when handing off the
 * already-loaded briefing so the rest of the page can stay loose.
 */
interface LandscapeSection {
  id: string;
  title: string;
  blurb: string;
  count: number;
  findings: Array<{
    id: string;
    title: string;
    description: string;
    severity: Severity;
    source: string;
    source_url?: string;
    count?: number;
  }>;
}

interface LandscapeReport {
  slug: string;
  type: 'landscape';
  title: string;
  date: string;
  date_range: string;
  range_start: string;
  range_end: string;
  generated_at: string;
  executive_summary: string;
  top_threats: LandscapeSection;
  trending_actors: LandscapeSection;
  key_incidents: LandscapeSection;
  recommended_actions: LandscapeSection;
  outlook: LandscapeSection;
  stats: {
    ransomware_victims: number;
    top_groups: number;
    incidents_surfaced: number;
    recommendations: number;
    sources: number;
  };
  sources: string[];
}

function StatPill({ label, value, accent }: { label: string; value: number | string; accent?: string }) {
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={`text-2xl font-display font-bold ${accent ?? 'text-slate-900 dark:text-slate-100'}`}>
        {value}
      </span>
      <span className="text-micro font-mono uppercase tracking-wider text-slate-500">{label}</span>
    </div>
  );
}

function MitreChip({ technique }: { technique: string }) {
  const href = `https://attack.mitre.org/techniques/${technique.replace('.', '/')}`;
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="text-xs font-mono px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-brand-600 dark:text-brand-400 border border-slate-200 dark:border-slate-800 hover:border-brand-500/40 transition-colors"
    >
      {technique}
    </a>
  );
}

function FindingCard({ finding }: { finding: BriefingFinding }) {
  const canon = canonSeverity(finding.severity);
  return (
    <article
      className={`rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-e1 p-5 ring-1 ${SEVERITY_RING[canon]}`}
    >
      <div className="flex items-start justify-between gap-3 mb-2">
        <h4 className="font-display font-bold text-base text-slate-900 dark:text-slate-100 leading-snug">
          {finding.title}
        </h4>
        <span
          className={`text-micro font-mono uppercase tracking-wider px-2 py-0.5 rounded border ${SEVERITY_TONE[canon]} shrink-0`}
        >
          {SEVERITY_LABEL[finding.severity]}
          {finding.cvss !== undefined && ` · ${finding.cvss.toFixed(1)}`}
        </span>
      </div>
      {finding.description && (
        <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed mb-3 line-clamp-6">
          {finding.description}
        </p>
      )}
      {finding.tags &&
        (finding.tags.cves.length > 0 || finding.tags.actors.length > 0 || finding.tags.sectors.length > 0) && (
          <div className="flex flex-wrap gap-1.5 mb-3">
            {finding.tags.cves.map((cve) => (
              <a
                key={`cve-${cve}`}
                href={`https://nvd.nist.gov/vuln/detail/${cve}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-micro font-mono px-1.5 py-0.5 rounded border border-rose-500/40 bg-rose-500/10 text-rose-700 dark:text-rose-300 hover:underline"
                title={`Look up ${cve} on NVD`}
              >
                {cve}
              </a>
            ))}
            {finding.tags.actors.map((a) => (
              <span
                key={`actor-${a.slug}`}
                className="text-micro font-mono px-1.5 py-0.5 rounded border border-violet-500/40 bg-violet-500/10 text-violet-700 dark:text-violet-300"
                title={a.mitre_id ? `MITRE ${a.mitre_id}` : 'actor name detected'}
              >
                actor:{a.slug}
                {a.mitre_id && <span className="opacity-70"> · {a.mitre_id}</span>}
              </span>
            ))}
            {finding.tags.sectors.map((s) => (
              <span
                key={`sector-${s}`}
                className="text-micro font-mono px-1.5 py-0.5 rounded border border-sky-500/40 bg-sky-500/10 text-sky-700 dark:text-sky-300"
                title="heuristic sector classification"
              >
                sector:{s}
              </span>
            ))}
          </div>
        )}
      <div className="flex flex-wrap items-center gap-2 text-mini font-mono text-slate-500">
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-800">
          {finding.source}
        </span>
        {finding.added && <span>added {finding.added}</span>}
        {finding.mitre_techniques.length > 0 && (
          <span className="flex flex-wrap gap-1">
            {finding.mitre_techniques.map((t) => (
              <MitreChip key={t} technique={t} />
            ))}
          </span>
        )}
        {finding.source_url && (
          <a
            href={sanitizeUrl(finding.source_url) || undefined}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-brand-600 dark:text-brand-400 hover:underline ml-auto"
          >
            details <ExternalLink size={11} />
          </a>
        )}
      </div>
    </article>
  );
}

type IocKind = 'url' | 'domain' | 'ipv4' | 'hash';

/** Build per-kind pivot links so each IOC offers more than just /dfir/ioc-check. */
function pivotsFor(kind: IocKind, value: string): Array<{ to: string; label: string }> {
  const enc = encodeURIComponent(value);
  const out: Array<{ to: string; label: string }> = [];
  switch (kind) {
    case 'url': {
      out.push({ to: `/dfir/url-preview?url=${enc}`, label: 'preview' });
      try {
        const host = new URL(value).hostname;
        out.push({ to: `/dfir/domain?domain=${encodeURIComponent(host)}`, label: 'domain' });
      } catch {
        /* malformed URL — skip the host pivot */
      }
      break;
    }
    case 'domain': {
      out.push({ to: `/dfir/domain?domain=${enc}`, label: 'inspect' });
      out.push({ to: `/dfir/cert-search?domain=${enc}`, label: 'certs' });
      out.push({ to: `/dfir/takeover?domain=${enc}`, label: 'takeover' });
      break;
    }
    case 'ipv4': {
      out.push({ to: `/dfir/ip-geo?ip=${enc}`, label: 'geo' });
      break;
    }
    case 'hash': {
      // IOC Checker reads ?indicator= and auto-runs the multi-provider lookup.
      out.push({ to: `/dfir/ioc-check?indicator=${enc}`, label: 'hash' });
      break;
    }
  }
  return out;
}

function IocTable({ title, kind, entries }: { title: string; kind: IocKind; entries: IocEntry[] }) {
  if (entries.length === 0) return null;
  return (
    <section className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-e1 p-5">
      <h3 className="font-display font-bold text-sm uppercase tracking-wider text-slate-700 dark:text-slate-300 mb-3">
        {title} <span className="text-slate-500 font-normal">({entries.length})</span>
      </h3>
      <div className="space-y-1.5 font-mono text-xs">
        {entries.map((e, i) => {
          const pivots = pivotsFor(kind, e.value);
          return (
            <div
              key={`${e.value}-${i}`}
              className="px-2 py-1 rounded hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors group"
            >
              <Link
                to={`/dfir/ioc-check?indicator=${encodeURIComponent(e.value)}`}
                className="block text-slate-700 dark:text-slate-300 hover:text-brand-600 dark:hover:text-brand-400 truncate"
                title={e.context}
              >
                {e.value}
                {e.context && <span className="text-slate-500 ml-2">— {e.context}</span>}
              </Link>
              {pivots.length > 0 && (
                <div className="flex flex-wrap gap-1 mt-0.5 ml-1">
                  {pivots.map((p) => (
                    <Link
                      key={p.label}
                      to={p.to}
                      className="text-micro uppercase tracking-wider px-1 py-0 rounded text-slate-500 hover:text-brand-600 dark:hover:text-brand-400"
                    >
                      → {p.label}
                    </Link>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

/**
 * Landscape-report specific view. Distinct from the daily/weekly view
 * because the data shape is different — landscape reports have named
 * sections (top_threats, trending_actors, key_incidents,
 * recommended_actions, outlook) rather than a generic sections[] array,
 * and they don't carry IOC tables.
 */
function LandscapeReportView({ briefing }: { briefing: LandscapeReport }): JSX.Element {
  const sections: Array<{
    key: keyof LandscapeReport;
    section: LandscapeSection;
    icon: typeof TrendingUp;
    accent: string;
  }> = [
    {
      key: 'top_threats',
      section: briefing.top_threats,
      icon: TrendingUp,
      accent: 'text-amber-600 dark:text-amber-400',
    },
    {
      key: 'trending_actors',
      section: briefing.trending_actors,
      icon: Users,
      accent: 'text-violet-600 dark:text-violet-400',
    },
    {
      key: 'key_incidents',
      section: briefing.key_incidents,
      icon: ListChecks,
      accent: 'text-rose-600 dark:text-rose-400',
    },
    {
      key: 'recommended_actions',
      section: briefing.recommended_actions,
      icon: ShieldAlert,
      accent: 'text-emerald-600 dark:text-emerald-400',
    },
    {
      key: 'outlook',
      section: briefing.outlook,
      icon: Compass,
      accent: 'text-sky-600 dark:text-sky-400',
    },
  ];
  const stats = briefing.stats;
  return (
    <>
      {/* Landscape KPI bar */}
      <section className="rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-e1 p-4 mb-8">
        <div className="flex flex-wrap items-center justify-around gap-6">
          <StatPill label="victims" value={stats.ransomware_victims} accent="text-rose-600 dark:text-rose-400" />
          <StatPill label="actors" value={stats.top_groups} accent="text-violet-600 dark:text-violet-400" />
          <StatPill label="incidents" value={stats.incidents_surfaced} accent="text-amber-600 dark:text-amber-400" />
          <StatPill label="actions" value={stats.recommendations} accent="text-emerald-600 dark:text-emerald-400" />
          <StatPill label="sources" value={stats.sources} accent="text-sky-600 dark:text-sky-400" />
        </div>
      </section>

      {/* Executive summary */}
      <section className="mb-10">
        <h2 className="font-display font-bold text-lg mb-3 flex items-center gap-2">
          <Sparkles size={18} className="text-brand-600 dark:text-brand-400" /> Executive Summary
        </h2>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{briefing.executive_summary}</p>
      </section>

      {/* Sections */}
      <section className="mb-12 space-y-8">
        {sections.map(({ key, section, icon: Icon, accent }) => (
          <div key={key as string}>
            <div className="flex items-baseline justify-between mb-2">
              <h2 className="font-display font-bold text-xl flex items-center gap-2">
                <Icon size={18} className={accent} />
                {section.title}
              </h2>
              <span className="text-xs font-mono text-slate-500">{section.count} items</span>
            </div>
            <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">{section.blurb}</p>
            <div className="space-y-3">
              {section.findings.map((f) => (
                <article
                  key={f.id}
                  className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-e1 p-5"
                >
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <h4 className="font-display font-bold text-base text-slate-900 dark:text-slate-100 leading-snug">
                      {f.title}
                    </h4>
                    {f.count !== undefined && (
                      <span className="text-micro font-mono uppercase tracking-wider px-2 py-0.5 rounded border bg-slate-100 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 shrink-0">
                        ×{f.count}
                      </span>
                    )}
                  </div>
                  {f.description && (
                    <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed mb-3 line-clamp-4">
                      {f.description}
                    </p>
                  )}
                  <div className="flex flex-wrap items-center gap-2 text-mini font-mono text-slate-500">
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-800">
                      {f.source}
                    </span>
                    {f.source_url && (
                      <a
                        href={sanitizeUrl(f.source_url) || undefined}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-brand-600 dark:text-brand-400 hover:underline ml-auto"
                      >
                        details <ExternalLink size={11} />
                      </a>
                    )}
                  </div>
                </article>
              ))}
            </div>
          </div>
        ))}
      </section>
    </>
  );
}

export default function BriefingDetail(): JSX.Element {
  const { slug } = useParams<{ slug: string }>();
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshKey, setRefreshKey] = useState(0);

  useEffect(() => {
    if (!slug) return;
    let cancelled = false;
    const ctrl = new AbortController();
    setLoading(true);
    setError(null);
    setBriefing(null);
    fetch(`/api/v1/briefings/${encodeURIComponent(slug)}`, { signal: ctrl.signal })
      .then(async (r) => {
        if (!r.ok) {
          const body = await r.text().catch(() => '');
          let msg = `${r.status}`;
          try {
            const parsed = JSON.parse(body) as { error?: string };
            msg = parsed.error ?? msg;
          } catch {
            /* use default */
          }
          throw new Error(msg);
        }
        const ct = r.headers.get('content-type') ?? '';
        if (!ct.includes('json')) throw new Error('Server returned non-JSON response');
        return (await r.json()) as Briefing;
      })
      .then((b) => {
        if (!cancelled) setBriefing(b);
      })
      .catch((err: { name?: string; message?: string }) => {
        if (cancelled || err.name === 'AbortError') return;
        setError(err.message ?? 'failed to load');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
      ctrl.abort();
    };
  }, [slug, refreshKey]);

  // Concatenate the briefing's narrative content into one body string the
  // intel extractor can scan — executive summary + every finding's title +
  // description. The flat-IoC tables further down stay as the human-friendly
  // browsing surface; the card adds the structured STIX 2.1 view on top.
  // Called before the conditional returns so it satisfies the rules-of-hooks
  // ordering invariant across renders.
  const intelBody = useMemo(() => {
    if (!briefing) return '';
    const parts: string[] = [briefing.executive_summary];
    // Landscape reports have a different structure — use named sections.
    if (briefing.type === 'landscape') {
      const lr = briefing as unknown as LandscapeReport;
      for (const section of [
        lr.top_threats,
        lr.trending_actors,
        lr.key_incidents,
        lr.recommended_actions,
        lr.outlook,
      ]) {
        parts.push(`\n\n## ${section.title}\n${section.blurb}`);
        for (const f of section.findings) {
          parts.push(`\n### ${f.title}\n${f.description}`);
        }
      }
    } else {
      for (const s of briefing.sections) {
        parts.push(`\n\n## ${s.title}\n${s.blurb}`);
        for (const f of s.findings) {
          parts.push(`\n### ${f.title}\n${f.description}`);
        }
      }
    }
    return parts.join('\n');
  }, [briefing]);

  if (loading) {
    return (
      <div className="max-w-5xl mx-auto px-4 sm:px-8 py-12 sm:py-16 font-mono text-sm text-slate-500">
        Loading briefing…
      </div>
    );
  }
  if (error || !briefing) {
    return (
      <div className="max-w-5xl mx-auto px-4 sm:px-8 py-12 sm:py-16">
        <Link
          to="/threatintel/briefings"
          className="inline-flex items-center gap-2 text-sm text-slate-500 mb-6 font-mono"
        >
          <ArrowLeft size={14} /> back
        </Link>
        <h1 className="font-display font-bold text-2xl text-slate-900 dark:text-slate-100 mb-2">Briefing not found</h1>
        <p className="text-sm text-slate-500">
          {error ??
            'This briefing has not been generated yet. Daily briefings publish at 00:05 UTC; weekly at 00:15 UTC Monday.'}
        </p>
        <button
          type="button"
          onClick={() => setRefreshKey((k) => k + 1)}
          className="mt-4 inline-flex items-center gap-1 text-meta font-mono px-2.5 py-1.5 rounded border border-slate-300 dark:border-slate-700 hover:border-brand-500/40"
        >
          retry
        </button>
      </div>
    );
  }

  const stats = briefing.stats;
  const shareUrl = typeof window !== 'undefined' ? window.location.href : '';
  const shareTitle = briefing.title;
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-8 py-12 text-slate-900 dark:text-slate-100">
      <Link
        to="/threatintel/briefings"
        className="inline-flex items-center gap-2 text-sm text-slate-600 dark:text-slate-400 hover:text-brand-600 dark:hover:text-brand-400 mb-8 font-mono transition-colors"
      >
        <ArrowLeft size={14} /> all briefings
      </Link>

      <header className="animate-fade-in-up mb-8">
        <span className="inline-block text-xs font-bold uppercase tracking-[0.2em] text-brand-600 dark:text-brand-400 mb-3">
          Intel Briefing · {briefing.type}
        </span>
        <h1 className="text-3xl sm:text-4xl font-display font-bold leading-tight mb-2">{briefing.title}</h1>
        <p className="text-sm font-mono text-slate-500 mb-3">
          {briefing.date_range} · generated {briefing.generated_at.slice(0, 16).replace('T', ' ')} UTC
        </p>
        <AutoGeneratedBadge kind="briefing" generatedAt={briefing.generated_at} variant="banner" />
        {briefing.degraded && (
          <div
            role="alert"
            className="mt-4 rounded-lg border border-amber-300 dark:border-amber-800/60 bg-amber-50 dark:bg-amber-900/15 p-4"
          >
            <div className="flex items-start gap-3">
              <AlertTriangle
                size={18}
                className="text-amber-700 dark:text-amber-400 shrink-0 mt-0.5"
                aria-hidden="true"
              />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-semibold text-amber-900 dark:text-amber-200">
                  Upstream feeds were unreachable when this briefing was built.
                </p>
                <p className="text-xs text-amber-800 dark:text-amber-300 mt-1 leading-relaxed">
                  CISA KEV and NVD returned errors from the edge at build time. The hourly self-heal will rebuild this
                  briefing as soon as the feeds respond — within an hour of recovery. This is{' '}
                  <span className="font-semibold">not</span> an all-clear; do not treat zero findings as &quot;no new
                  vulnerabilities&quot;.
                </p>
                <button
                  type="button"
                  onClick={() => setRefreshKey((k) => k + 1)}
                  className="mt-3 inline-flex items-center gap-1.5 text-xs font-mono px-2.5 py-1.5 rounded border border-amber-400/60 text-amber-900 dark:text-amber-200 hover:bg-amber-500/10"
                >
                  retry now
                </button>
              </div>
            </div>
          </div>
        )}
        <a
          href={`/api/v1/briefings/${briefing.slug}/print`}
          target="_blank"
          className="mt-3 inline-flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 hover:border-brand-500/40 hover:bg-brand-500/5 transition-colors"
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          Print / PDF
        </a>
        <div className="mt-3 flex items-center gap-2">
          <a
            href={`https://x.com/intent/tweet?text=${encodeURIComponent(shareTitle)}&url=${encodeURIComponent(shareUrl)}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 hover:border-brand-500/40 hover:bg-brand-500/5 transition-colors"
          >
            <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
            X
          </a>
          <a
            href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 hover:border-brand-500/40 hover:bg-brand-500/5 transition-colors"
          >
            <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
            </svg>
            LinkedIn
          </a>
        </div>
      </header>

      {/* Landscape reports have their own section layout — branch before the
          daily/weekly findings/IOC tables render. */}
      {briefing.type === 'landscape' && <LandscapeReportView briefing={briefing as unknown as LandscapeReport} />}

      {/* Stats bar — daily/weekly only; landscape has its own stats in LandscapeReportView. */}
      {briefing.type !== 'landscape' && (
        <section className="rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-e1 p-4 mb-8">
          <div className="flex flex-wrap items-center justify-around gap-6">
            <StatPill label="findings" value={stats.findings} />
            <StatPill label="sections" value={stats.sections} />
            <StatPill label="CVEs" value={stats.cves} />
            <StatPill label="KEVs" value={stats.kevs} />
            <StatPill label="IOCs" value={stats.iocs} />
            <StatPill label="critical" value={stats.critical} accent="text-rose-600 dark:text-rose-400" />
            <StatPill label="high" value={stats.high} accent="text-orange-600 dark:text-orange-400" />
            <StatPill label="medium" value={stats.medium} accent="text-amber-600 dark:text-amber-400" />
            <StatPill label="low" value={stats.low} accent="text-slate-600 dark:text-slate-300" />
          </div>
        </section>
      )}

      {/* Structured STIX 2.1 intel view. Renders an enriched card backed by
          /api/v1/intel-bundle — heuristic-extracted actors, malware, CVEs,
          theme tags + bulk-enriched IoCs with risk scores. Falls back to
          rendering nothing while loading so the Executive Summary still
          carries the page on first paint. */}
      <section className="mb-10">
        <IntelCard
          sourceId="briefings"
          itemRef={briefing.slug}
          item={{
            title: briefing.title,
            body: intelBody,
            publishedAt: briefing.generated_at,
          }}
          fallback={null}
        />
      </section>

      {/* Executive Summary */}
      <section className="mb-10">
        <h2 className="font-display font-bold text-lg mb-3 flex items-center gap-2">
          <ShieldAlert size={18} className="text-brand-600 dark:text-brand-400" /> Executive Summary
        </h2>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{briefing.executive_summary}</p>
      </section>

      {/* Sections — daily/weekly only; landscape uses LandscapeReportView above */}
      {briefing.type !== 'landscape' && briefing.sections && briefing.sections.length > 0 && (
        <section className="mb-12 space-y-8">
          {briefing.sections.map((s) => (
            <div key={s.id}>
              <div className="flex items-baseline justify-between mb-2">
                <h2 className="font-display font-bold text-xl flex items-center gap-2">
                  <AlertTriangle size={18} className="text-brand-600 dark:text-brand-400" />
                  {s.title}
                </h2>
                <span className="text-xs font-mono text-slate-500">
                  {s.count} {s.count === 1 ? 'finding' : 'findings'}
                </span>
              </div>
              <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">{s.blurb}</p>
              <div className="space-y-3">
                {s.findings.map((f) => (
                  <FindingCard key={f.id} finding={f} />
                ))}
              </div>
            </div>
          ))}
        </section>
      )}

      {/* MITRE techniques observed — daily/weekly only */}
      {briefing.type !== 'landscape' && briefing.mitre_techniques && briefing.mitre_techniques.length > 0 && (
        <section className="mb-10">
          <h2 className="font-display font-bold text-lg mb-3">MITRE ATT&amp;CK Techniques Observed</h2>
          <div className="flex flex-wrap gap-2">
            {briefing.mitre_techniques.map((t) => (
              <MitreChip key={t} technique={t} />
            ))}
          </div>
        </section>
      )}

      {/* IOCs — daily/weekly only */}
      {briefing.type !== 'landscape' &&
        briefing.iocs &&
        (briefing.iocs.urls.length > 0 ||
          briefing.iocs.domains.length > 0 ||
          briefing.iocs.ipv4s.length > 0 ||
          briefing.iocs.hashes.length > 0) && (
          <section className="mb-10">
            <h2 className="font-display font-bold text-lg mb-4">Active Threat Indicators</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <IocTable title="URLs" kind="url" entries={briefing.iocs.urls} />
              <IocTable title="Domains" kind="domain" entries={briefing.iocs.domains} />
              <IocTable title="IPv4" kind="ipv4" entries={briefing.iocs.ipv4s} />
              <IocTable title="Hashes" kind="hash" entries={briefing.iocs.hashes} />
            </div>
          </section>
        )}

      {/* Footer */}
      <footer className="mt-12 pt-6 border-t border-slate-200 dark:border-slate-800 text-xs font-mono text-slate-500">
        <p>
          Sources: {briefing.sources.join(', ') || 'none'}. Reference only. Verify all indicators in your own
          environment. Generated {briefing.generated_at.slice(0, 16).replace('T', ' ')} UTC.
        </p>
      </footer>
    </div>
  );
}
