import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

/**
 * Route source-of-truth drift guard.
 *
 * Three files must agree about which routes exist and which are prerendered:
 *   - src/App.tsx          — the ROUTES / REDIRECTS table (what routes exist)
 *   - scripts/prerender.mjs — the ROUTES array (what gets SSR'd to dist/__prerendered)
 *   - worker/router.ts     — PRERENDERED_ROUTES (what the Worker serves as prerendered)
 *
 * PR #83 had to hand-fix 12 drifted DFIR routes; this guards that bug class in
 * CI (pure file read, no build, <1s) instead of relying on someone noticing a
 * 404 — or a prerendered NotFound page served as the real page — in prod.
 */

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = (p: string): string => readFileSync(join(root, p), 'utf8');

/** Static + redirect paths declared in App.tsx's data-driven ROUTES/REDIRECTS tables. */
function appRoutePaths(): Set<string> {
  const src = read('src/App.tsx');
  const out = new Set<string>();
  for (const m of src.matchAll(/\{\s*path:\s*'([^']+)',\s*Component:/g)) out.add(m[1]);
  for (const m of src.matchAll(/\{\s*path:\s*'([^']+)',\s*to:\s*'[^']+'/g)) out.add(m[1]);
  return out;
}

/** Absolute paths in scripts/prerender.mjs's ROUTES array (what is SSR-rendered at build). */
function prerenderPaths(): string[] {
  const src = read('scripts/prerender.mjs');
  const start = src.indexOf('const ROUTES = [');
  const block = src.slice(start, src.indexOf('\n]', start));
  return [...block.matchAll(/'(\/[^']*)'/g)].map((m) => m[1]);
}

/** Keys of worker/router.ts's PRERENDERED_ROUTES map (what the Worker serves as prerendered). */
function routerPrerenderedKeys(): string[] {
  const src = read('worker/router.ts');
  const start = src.indexOf('PRERENDERED_ROUTES = new Map');
  const block = src.slice(start, src.indexOf('])', start));
  return [...block.matchAll(/\[\s*'([^']+)'\s*,\s*'\/__prerendered/g)].map((m) => m[1]);
}

describe('route source-of-truth drift guard', () => {
  it('every prerendered route is a real App.tsx route or redirect', () => {
    const app = appRoutePaths();
    expect(app.size, 'App.tsx route extraction failed — adjust the regex').toBeGreaterThan(50);
    const orphans = prerenderPaths().filter((p) => !app.has(p));
    expect(
      orphans,
      `scripts/prerender.mjs ROUTES contains paths with no <Route> or redirect in src/App.tsx — drift: ${orphans.join(', ')}`
    ).toEqual([]);
  });

  it('every Worker-served prerendered route is actually generated by prerender.mjs', () => {
    const pre = new Set(prerenderPaths());
    expect(pre.size, 'prerender.mjs ROUTES extraction failed — adjust the regex').toBeGreaterThan(50);
    const missing = routerPrerenderedKeys().filter((k) => !pre.has(k));
    expect(
      missing,
      `worker/router.ts PRERENDERED_ROUTES serves paths that scripts/prerender.mjs never generates (would 404) — drift: ${missing.join(', ')}`
    ).toEqual([]);
  });
});
