import { useEffect, useState, useRef, useCallback, useMemo } from 'react';
import { Link, useParams } from 'react-router-dom';
import { DataState } from '../components/DataState';
import { AutoGeneratedBadge } from '../components/AutoGeneratedBadge';
import { estimateReadingTime, generateHashtags, findRelatedPosts } from '../lib/content-utils';
import { extractFaq } from '../lib/faq-schema';

interface Post {
  slug: string;
  title: string;
  type: string;
  publishedAt: string;
  body: string;
  hero: string;
  heroImageUrl?: string;
  iocs: { type: string; value: string }[];
  tags: string[];
  sources?: { url: string; title: string }[];
  candidateId?: string;
  quality?: { total: number };
}

interface PostIndexEntry {
  slug: string;
  title: string;
  type: string;
  excerpt: string;
  publishedAt: string;
  tags: string[];
}

interface TocItem {
  id: string;
  text: string;
  level: number;
}

const PROSE =
  '[&_h2]:font-display [&_h2]:text-xl [&_h2]:font-bold [&_h2]:mt-10 [&_h2]:mb-3 [&_h2]:text-slate-900 dark:[&_h2]:text-slate-100 ' +
  '[&_h3]:font-display [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:mt-8 [&_h3]:mb-2 [&_h3]:text-slate-800 dark:[&_h3]:text-slate-200 ' +
  '[&_p]:text-slate-700 dark:[&_p]:text-slate-300 [&_p]:leading-relaxed [&_p]:mb-4 ' +
  '[&_a]:text-brand-600 dark:[&_a]:text-brand-400 [&_a]:hover:underline ' +
  '[&_strong]:text-slate-900 dark:[&_strong]:text-slate-100 ' +
  '[&_code]:text-brand-700 dark:[&_code]:text-brand-300 [&_code]:bg-slate-100 dark:[&_code]:bg-slate-800 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-sm [&_code]:font-mono ' +
  '[&_pre]:bg-slate-50 dark:[&_pre]:bg-slate-900 [&_pre]:border [&_pre]:border-slate-200 dark:[&_pre]:border-slate-800 [&_pre]:p-4 [&_pre]:rounded-xl [&_pre]:mb-4 [&_pre]:overflow-x-auto ' +
  '[&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-4 [&_ul]:text-slate-700 dark:[&_ul]:text-slate-300 ' +
  '[&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:mb-4 [&_ol]:text-slate-700 dark:[&_ol]:text-slate-300 [&_li]:mb-1 ' +
  '[&_blockquote]:border-l-4 [&_blockquote]:border-brand-500 dark:[&_blockquote]:border-brand-400 [&_blockquote]:pl-4 [&_blockquote]:italic [&_blockquote]:text-slate-600 dark:[&_blockquote]:text-slate-400 [&_blockquote]:mb-4 ' +
  '[&_hr]:border-slate-200 dark:[&_hr]:border-slate-800 [&_hr]:my-8 ' +
  '[&_table]:w-full [&_table]:border-collapse [&_table]:mb-4 ' +
  '[&_th]:border [&_th]:border-slate-200 dark:[&_th]:border-slate-800 [&_th]:p-2 [&_th]:text-left [&_th]:text-slate-800 dark:[&_th]:text-slate-200 [&_th]:bg-slate-50 dark:[&_th]:bg-slate-900 ' +
  '[&_td]:border [&_td]:border-slate-200 dark:[&_td]:border-slate-800 [&_td]:p-2 [&_td]:text-slate-700 dark:[&_td]:text-slate-300 ' +
  '[&_img]:rounded-xl [&_img]:mb-4 [&_img]:max-w-full ' +
  '[&_details]:mb-4 [&_details]:rounded-xl [&_details]:border [&_details]:border-slate-200 dark:[&_details]:border-slate-700 [&_details]:bg-slate-50/50 dark:[&_details]:bg-slate-900/20 [&_details]:overflow-hidden ' +
  '[&_summary]:cursor-pointer [&_summary]:px-4 [&_summary]:py-2.5 [&_summary]:font-mono [&_summary]:text-xs [&_summary]:uppercase [&_summary]:tracking-[0.16em] [&_summary]:text-brand-600 dark:[&_summary]:text-brand-400 [&_summary]:select-none [&_summary]:hover:text-brand-500 ' +
  '[&_details_>_:not(summary)]:px-4 [&_details_>_:not(summary)]:pb-3 [&_details_>_:not(summary)]:text-sm';

function addHeadingIds(html: string): string {
  let index = 0;
  return html.replace(/<h([23])[^>]*>([^<]+)<\/h[23]>/g, (_match, level, text) => {
    const cleanText = text.replace(/<[^>]+>/g, '').trim();
    const id =
      cleanText
        .toLowerCase()
        .replace(/[^\w\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-+|-+$/g, '') || `heading-${index}`;
    index++;
    return `<h${level} id="${id}">${text}</h${level}>`;
  });
}

function extractToc(html: string): TocItem[] {
  const items: TocItem[] = [];
  const regex = /<h([23])\s+id="([^"]+)">([^<]+)<\/h[23]>/g;
  let match;
  while ((match = regex.exec(html)) !== null) {
    items.push({
      level: parseInt(match[1]!),
      id: match[2]!,
      text: match[3]!,
    });
  }
  return items;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export default function BlogPost() {
  const { slug } = useParams();
  const [post, setPost] = useState<Post | null>(null);
  const [notFound, setNotFound] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [html, setHtml] = useState<string>('');
  const [tocItems, setTocItems] = useState<TocItem[]>([]);
  const [activeTocId, setActiveTocId] = useState<string>('');
  const [relatedPosts, setRelatedPosts] = useState<PostIndexEntry[]>([]);
  const [reloadKey, setReloadKey] = useState(0);
  const [tocOpen, setTocOpen] = useState(false);
  // Reading-progress state — drives a thin progress bar at the top of
  // the page so readers know how far through the case study they are.
  // Updated by a passive scroll listener mounted below. 0-100.
  const [readingProgress, setReadingProgress] = useState(0);
  const articleRef = useRef<HTMLElement>(null);

  // Set Open Graph meta tags for social sharing
  useEffect(() => {
    if (!post) return;
    const description = post.body
      .replace(/<[^>]+>/g, '')
      .replace(/[#*`>_[\]]/g, '')
      .trim()
      .slice(0, 160);
    const url = `https://pranithjain.qzz.io/blog/${post.slug}`;

    // Update document title
    document.title = `${post.title} — Pranith Jain`;

    // Set or update meta tags
    const setMeta = (property: string, content: string) => {
      let el = document.querySelector(`meta[property="${property}"]`) as HTMLMetaElement;
      if (!el) {
        el = document.createElement('meta');
        el.setAttribute('property', property);
        document.head.appendChild(el);
      }
      el.setAttribute('content', content);
    };

    setMeta('og:title', post.title);
    setMeta('og:description', description);
    setMeta('og:url', url);
    setMeta('og:type', 'article');
    setMeta('og:site_name', 'Pranith Jain — CTI Portfolio');
    setMeta('article:published_time', post.publishedAt);
    setMeta('article:author', 'Pranith Jain');
    if (post.tags.length > 0) setMeta('article:tag', post.tags.join(','));

    // Twitter Card
    let twitterCard = document.querySelector('meta[name="twitter:card"]') as HTMLMetaElement;
    if (!twitterCard) {
      twitterCard = document.createElement('meta');
      twitterCard.setAttribute('name', 'twitter:card');
      document.head.appendChild(twitterCard);
    }
    twitterCard.setAttribute('content', 'summary_large_image');

    // Cleanup on unmount
    return () => {
      document.title = 'Pranith Jain — CTI Portfolio';
    };
  }, [post]);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    setNotFound(false);
    setPost(null);
    setHtml('');
    setTocItems([]);
    setRelatedPosts([]);
    fetch(`/api/v1/blog/posts/${encodeURIComponent(slug ?? '')}`)
      .then(async (r) => {
        if (r.status === 404 || r.status === 400) {
          if (!cancelled) setNotFound(true);
          return;
        }
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        const data = (await r.json()) as { post: Post; bodyHtml: string };
        if (cancelled) return;
        setPost(data.post);
        const { default: DOMPurify } = await import('isomorphic-dompurify');
        if (cancelled) return;
        const sanitized = DOMPurify.sanitize(data.bodyHtml ?? '', {
          ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|#|\/):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
          ADD_ATTR: ['title'],
        });
        const withIds = addHeadingIds(sanitized);
        const toc = extractToc(withIds);
        setHtml(withIds);
        setTocItems(toc);
      })
      .catch((e: Error) => {
        if (!cancelled) setError(e.message);
      });
    return () => {
      cancelled = true;
    };
  }, [slug, reloadKey]);

  useEffect(() => {
    if (!html || !articleRef.current) return;
    const headings = articleRef.current.querySelectorAll('h2, h3');
    if (headings.length === 0) return;
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveTocId(entry.target.id);
          }
        });
      },
      { rootMargin: '-80px 0px -75% 0px' }
    );
    headings.forEach((h) => observer.observe(h));
    return () => observer.disconnect();
  }, [html]);

  // Reading-progress listener. Cheap — one rAF, no resize observer. Bound
  // to the post slug so we reset to 0 when navigating between case studies.
  useEffect(() => {
    let raf = 0;
    const onScroll = () => {
      if (raf) return;
      raf = window.requestAnimationFrame(() => {
        raf = 0;
        const doc = document.documentElement;
        const max = doc.scrollHeight - doc.clientHeight;
        const pct = max > 0 ? Math.min(100, Math.max(0, (window.scrollY / max) * 100)) : 0;
        setReadingProgress(pct);
      });
    };
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => {
      window.removeEventListener('scroll', onScroll);
      if (raf) window.cancelAnimationFrame(raf);
    };
  }, [post?.slug]);

  useEffect(() => {
    if (!slug || !post) return;
    let cancelled = false;
    fetch('/api/v1/blog/posts')
      .then((r) => r.json())
      .then((data) => {
        if (cancelled) return;
        const posts = (data.posts ?? []) as PostIndexEntry[];
        // Use relevance-based related posts algorithm
        const related = findRelatedPosts(
          { slug: post.slug, title: post.title, tags: post.tags, type: post.type },
          posts.map((p) => ({ slug: p.slug, title: p.title, tags: p.tags, type: p.type })),
          3
        );
        setRelatedPosts(posts.filter((p) => related.some((r) => r.slug === p.slug)));
      })
      .catch(() => {
        /* related posts are non-critical */
      });
    return () => {
      cancelled = true;
    };
  }, [slug, post]);

  const scrollToHeading = useCallback((id: string) => {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, []);

  const readTime = post ? estimateReadingTime(post.body) : 0;
  const shareUrl = typeof window !== 'undefined' ? window.location.href : '';
  const shareText = post?.title || '';
  const hashtags = useMemo(
    () => (post ? generateHashtags(post.title, post.body, post.tags, { platform: 'twitter', max: 3 }) : []),
    [post]
  );

  return (
    <article ref={articleRef} className="blog-post mx-auto max-w-5xl text-slate-900 dark:text-slate-100">
      <style>{`
        .blog-post details[open] summary {
          border-bottom: 1px solid rgb(226 232 240);
          margin-bottom: 0.5rem;
        }
        .dark .blog-post details[open] summary {
          border-bottom-color: rgb(51 65 85);
        }
        .blog-post details[open] > :not(summary) {
          padding-bottom: 0.75rem;
        }
        .blog-post .tldr-box {
          background: linear-gradient(to right, rgb(239 246 255), rgb(238 242 255));
          border-left: 4px solid rgb(99 102 241);
          border-radius: 0.5rem;
          padding: 1.25rem 1.5rem;
          margin-bottom: 1.5rem;
        }
        .dark .blog-post .tldr-box {
          background: linear-gradient(to right, rgb(30 27 75), rgb(15 23 42));
          border-left-color: rgb(99 102 241);
        }
      `}</style>
      {/* Reading-progress bar. Positioned at the very top of the article
          (sticky to the page, not the article, so it sits below the
          portfolio nav). One CSS variable drives the fill so we don't
          re-render the DOM on every scroll tick — only the inline
          transform. */}
      <div
        aria-hidden="true"
        className="sticky top-0 z-10 -mx-4 sm:-mx-6 lg:-mx-10 h-0.5 bg-transparent pointer-events-none"
      >
        <div
          className="h-full bg-brand-500 dark:bg-brand-400 origin-left transition-transform duration-150 ease-out"
          style={{ transform: `scaleX(${readingProgress / 100})` }}
        />
      </div>
      <Link
        to="/blog"
        className="inline-flex items-center gap-1 text-xs font-mono uppercase tracking-[0.16em] text-slate-500 hover:text-brand-600 dark:hover:text-brand-400 mb-6"
      >
        ← Back to Blog
      </Link>

      <DataState
        loading={!post && !notFound && !error}
        error={error}
        empty={notFound}
        emptyLabel="Post not found. It may have been unpublished."
        onRetry={() => setReloadKey((k) => k + 1)}
        rows={8}
      >
        {post && (
          <>
            <script
              type="application/ld+json"
              // Article structured data for richer SERP/article cards. Fields are
              // our own blog data; `<` is escaped so an author-supplied title
              // can't break out of the JSON-LD <script> block.
              dangerouslySetInnerHTML={{
                __html: JSON.stringify({
                  '@context': 'https://schema.org',
                  '@type': 'BlogPosting',
                  headline: post.title,
                  description: post.body
                    .replace(/<[^>]+>/g, '')
                    .replace(/[#*`>_[\]]/g, '')
                    .trim()
                    .slice(0, 200),
                  datePublished: post.publishedAt,
                  dateModified: post.publishedAt,
                  url: `https://pranithjain.qzz.io/blog/${post.slug}`,
                  mainEntityOfPage: `https://pranithjain.qzz.io/blog/${post.slug}`,
                  author: {
                    '@type': 'Person',
                    name: 'Pranith Jain',
                    url: 'https://pranithjain.qzz.io',
                    // sameAs disambiguates the author entity across platforms —
                    // a measured lift for getting cited by AI answer engines.
                    sameAs: ['https://www.linkedin.com/in/pranithjain', 'https://x.com/Npj8448'],
                  },
                  publisher: { '@type': 'Person', name: 'Pranith Jain' },
                  keywords: post.tags.join(', '),
                }).replace(/</g, '\\u003c'),
              }}
            />
            <script
              type="application/ld+json"
              dangerouslySetInnerHTML={{
                __html: JSON.stringify({
                  '@context': 'https://schema.org',
                  '@type': 'BreadcrumbList',
                  itemListElement: [
                    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://pranithjain.qzz.io' },
                    { '@type': 'ListItem', position: 2, name: 'Case Studies', item: 'https://pranithjain.qzz.io/blog' },
                    {
                      '@type': 'ListItem',
                      position: 3,
                      name: post.title,
                      item: `https://pranithjain.qzz.io/blog/${post.slug}`,
                    },
                  ],
                }).replace(/</g, '\\u003c'),
              }}
            />
            {(() => {
              // FAQPage structured data, derived from the post's `## FAQ`
              // section. Emits only when ≥2 Q&A pairs parse — the highest-
              // weighted answer-engine signal; absent FAQ → no script.
              const faq = extractFaq(post.body);
              if (faq.length < 2) return null;
              return (
                <script
                  type="application/ld+json"
                  dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                      '@context': 'https://schema.org',
                      '@type': 'FAQPage',
                      mainEntity: faq.map((f) => ({
                        '@type': 'Question',
                        name: f.question,
                        acceptedAnswer: { '@type': 'Answer', text: f.answer },
                      })),
                    }).replace(/</g, '\\u003c'),
                  }}
                />
              );
            })()}
            {post.tags.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mb-4">
                {post.tags.map((t) => (
                  <Link
                    key={t}
                    to={`/blog/c/${t}`}
                    className="rounded border border-slate-200 bg-slate-50 px-2.5 py-0.5 text-mini font-mono text-slate-600 hover:text-brand-600 hover:border-brand-300 dark:border-[rgb(var(--border-400))] dark:bg-[rgb(var(--surface-200))] dark:text-slate-400 dark:hover:text-brand-400 dark:hover:border-brand-700 transition-colors"
                  >
                    {t}
                  </Link>
                ))}
              </div>
            )}

            <img
              className="mb-6 w-full h-auto rounded-xl border border-slate-200 dark:border-[rgb(var(--border-400))]"
              alt={`Hero visual for ${post.title}`}
              width={1200}
              height={630}
              loading="lazy"
              src={post.heroImageUrl ?? `data:image/svg+xml;utf8,${encodeURIComponent(post.hero)}`}
            />

            <header className="mb-8">
              <Link
                to={`/blog/c/${post.type}`}
                className="text-eyebrow font-mono uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400 hover:underline"
              >
                {post.type}
              </Link>
              <h1 className="font-display text-3xl font-bold tracking-tight mt-1">{post.title}</h1>
              <div className="flex flex-wrap items-center gap-x-1.5 gap-y-1 text-sm text-slate-500 mt-3">
                <span>Pranith Jain</span>
                <span aria-hidden="true">·</span>
                <time>{formatDate(post.publishedAt)}</time>
                <span aria-hidden="true">·</span>
                <span>{readTime} min read</span>
                {post.quality && (
                  <>
                    <span aria-hidden="true">·</span>
                    <span
                      className={
                        'inline-flex items-center gap-1 rounded border px-1.5 py-0.5 font-mono text-micro uppercase tracking-wider ' +
                        (post.quality.total >= 70
                          ? 'border-emerald-400/40 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300'
                          : post.quality.total >= 50
                            ? 'border-amber-400/40 bg-amber-500/10 text-amber-700 dark:text-amber-300'
                            : 'border-rose-400/40 bg-rose-500/10 text-rose-700 dark:text-rose-300')
                      }
                      title={`Quality score ${post.quality.total}/100 — based on length, sections, depth, technical density, references, and filler penalty`}
                    >
                      Quality {post.quality.total}
                    </span>
                  </>
                )}
              </div>
              {post.candidateId && !post.candidateId.startsWith('manual-') && (
                <div className="mt-4">
                  <AutoGeneratedBadge kind="case-study" generatedAt={post.publishedAt} variant="banner" />
                </div>
              )}
            </header>

            {tocItems.length > 0 && (
              <div className="lg:hidden mb-6 surface-card">
                <button
                  type="button"
                  onClick={() => setTocOpen((v) => !v)}
                  className="flex w-full items-center justify-between px-4 py-3 text-xs font-mono uppercase tracking-[0.16em] text-slate-500"
                  aria-expanded={tocOpen}
                >
                  Table of Contents
                  <svg
                    className={`h-3 w-3 transition-transform ${tocOpen ? 'rotate-180' : ''}`}
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    aria-hidden="true"
                  >
                    <path d="M6 9l6 6 6-6" />
                  </svg>
                </button>
                {tocOpen && (
                  <nav className="border-t border-slate-200 dark:border-[rgb(var(--border-400))] px-4 py-3 space-y-1">
                    {tocItems.map((item) => (
                      <button
                        key={item.id}
                        type="button"
                        onClick={() => {
                          scrollToHeading(item.id);
                          setTocOpen(false);
                        }}
                        className={`block w-full text-left text-sm transition-colors py-1 ${
                          item.level === 3 ? 'pl-4 text-xs' : ''
                        } ${
                          activeTocId === item.id
                            ? 'text-brand-600 dark:text-brand-400 font-semibold'
                            : 'text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200'
                        }`}
                      >
                        {item.text}
                      </button>
                    ))}
                  </nav>
                )}
              </div>
            )}

            <div className="lg:grid lg:grid-cols-[1fr_220px] lg:gap-8">
              <div className={PROSE} dangerouslySetInnerHTML={{ __html: html }} />

              {tocItems.length > 0 && (
                <aside className="hidden lg:block">
                  <div className="sticky top-24">
                    <h4 className="text-xs font-mono uppercase tracking-[0.16em] text-slate-500 mb-3">
                      Table of Contents
                    </h4>
                    <nav className="space-y-1">
                      {tocItems.map((item) => (
                        <button
                          key={item.id}
                          type="button"
                          onClick={() => scrollToHeading(item.id)}
                          className={`block w-full text-left transition-colors py-1 ${
                            item.level === 3 ? 'pl-3 text-xs' : 'text-sm'
                          } ${
                            activeTocId === item.id
                              ? 'text-brand-600 dark:text-brand-400 font-semibold'
                              : 'text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200'
                          }`}
                        >
                          {item.text}
                        </button>
                      ))}
                    </nav>
                  </div>
                </aside>
              )}
            </div>

            <div className="mt-8 flex items-center gap-3 pt-6 border-t border-slate-200 dark:border-[rgb(var(--border-400))]">
              <span className="text-xs font-mono uppercase tracking-[0.16em] text-slate-500">Share</span>
              <a
                href={`https://x.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 rounded border border-slate-200 dark:border-[rgb(var(--border-400))] px-3 py-1.5 text-xs font-semibold text-muted hover:bg-slate-50 dark:hover:bg-[rgb(var(--surface-300))] hover:border-brand-300 dark:hover:border-brand-700 transition-colors"
              >
                <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
                  <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                </svg>
                X
              </a>
              <a
                href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 rounded border border-slate-200 dark:border-[rgb(var(--border-400))] px-3 py-1.5 text-xs font-semibold text-muted hover:bg-slate-50 dark:hover:bg-[rgb(var(--surface-300))] hover:border-brand-300 dark:hover:border-brand-700 transition-colors"
              >
                <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                </svg>
                LinkedIn
              </a>
              {hashtags.length > 0 && (
                <span className="text-mini font-mono text-slate-400 dark:text-slate-500">
                  {hashtags.map((h) => `#${h}`).join(' ')}
                </span>
              )}
            </div>

            {post.iocs.length > 0 && (
              <aside className="mt-8 border-t border-slate-200 dark:border-[rgb(var(--border-400))] pt-6">
                <h2 className="text-mini font-mono uppercase tracking-[0.16em] text-slate-500 mb-2">IOCs</h2>
                <ul className="text-sm font-mono space-y-1">
                  {post.iocs.map((i, k) => (
                    <li key={`${i.type}-${i.value}-${k}`}>
                      <Link
                        to={`/dfir/ioc-check?q=${encodeURIComponent(i.value)}`}
                        className="text-slate-700 dark:text-slate-300 hover:text-brand-600 dark:hover:text-brand-400 hover:underline"
                      >
                        [{i.type}] {i.value}
                      </Link>
                    </li>
                  ))}
                </ul>
              </aside>
            )}

            {/* Author Bio */}
            <section className="mt-10 surface-card p-6 sm:p-8">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0">
                  <div className="h-16 w-16 rounded-full bg-brand-100 dark:bg-brand-900/30 flex items-center justify-center">
                    <span className="text-2xl font-display font-bold text-brand-600 dark:text-brand-400">PJ</span>
                  </div>
                </div>
                <div>
                  <h3 className="font-display text-lg font-bold text-slate-900 dark:text-white">Pranith Jain</h3>
                  <p className="text-sm text-muted mt-1">
                    Detection & response practitioner specializing in threat intelligence, email security, and cloud
                    identity. Building tools that make CTI accessible to everyone.
                  </p>
                  <div className="flex gap-3 mt-3">
                    <Link to="/about" className="text-xs font-mono text-brand-600 dark:text-brand-400 hover:underline">
                      About
                    </Link>
                    <a
                      href="https://x.com/Npj8448"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs font-mono text-brand-600 dark:text-brand-400 hover:underline"
                    >
                      X/Twitter
                    </a>
                    <a
                      href="https://linkedin.com/in/pranithjain"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs font-mono text-brand-600 dark:text-brand-400 hover:underline"
                    >
                      LinkedIn
                    </a>
                  </div>
                </div>
              </div>
            </section>

            {post.sources && post.sources.length > 0 && (
              <section className="mt-6 surface-card p-6 sm:p-8">
                <h2 className="text-mini font-mono uppercase tracking-[0.16em] text-slate-500 mb-3">Sources</h2>
                <ul className="space-y-2">
                  {post.sources.map((s, i) => (
                    <li key={i} className="text-sm">
                      <a
                        href={s.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-brand-600 dark:text-brand-400 hover:underline font-medium"
                      >
                        {s.title || s.url}
                      </a>
                      {s.title && (
                        <span className="text-slate-500 dark:text-slate-400 ml-1">
                          — {s.url.replace(/^https?:\/\//, '').replace(/\/$/, '')}
                        </span>
                      )}
                    </li>
                  ))}
                </ul>
              </section>
            )}

            <section className="mt-6 surface-card p-6 sm:p-8">
              <div className="sm:flex sm:items-center sm:justify-between gap-6">
                <div className="mb-4 sm:mb-0">
                  <h3 className="font-display text-xl font-bold text-slate-900 dark:text-white">
                    Try the DFIR Toolkit
                  </h3>
                  <p className="mt-1 text-sm text-muted leading-relaxed">
                    Free, edge-hosted tools for IOC enrichment, email analysis, and live threat intelligence. No signup,
                    no rate limits on core tools.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2 shrink-0">
                  <Link
                    to="/dfir"
                    className="inline-flex items-center gap-1.5 rounded bg-brand-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-brand-500"
                  >
                    Open DFIR Toolkit
                  </Link>
                  <Link
                    to="/threatintel"
                    className="inline-flex items-center gap-1.5 rounded border border-slate-300 dark:border-[rgb(var(--border-400))] px-4 py-2 text-sm font-semibold text-slate-700 dark:text-slate-300 transition hover:bg-slate-50 dark:hover:bg-[rgb(var(--surface-300))]"
                  >
                    Threat Intel
                  </Link>
                </div>
              </div>
              <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500 dark:text-slate-400">
                <span className="flex items-center gap-1.5">
                  <span className="h-1.5 w-1.5 rounded-full bg-brand-500" aria-hidden="true" />
                  IOC Check
                </span>
                <span className="flex items-center gap-1.5">
                  <span className="h-1.5 w-1.5 rounded-full bg-brand-500" aria-hidden="true" />
                  Phishing Analysis
                </span>
                <span className="flex items-center gap-1.5">
                  <span className="h-1.5 w-1.5 rounded-full bg-brand-500" aria-hidden="true" />
                  Live Threat Intel
                </span>
                <span className="flex items-center gap-1.5">
                  <span className="h-1.5 w-1.5 rounded-full bg-brand-500" aria-hidden="true" />
                  REST API & CLI
                </span>
              </div>
            </section>

            {relatedPosts.length > 0 && (
              <section className="mt-10">
                <h2 className="text-xs font-mono uppercase tracking-[0.16em] text-slate-500 mb-4">Related Research</h2>
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {relatedPosts.map((p) => {
                    const relatedReadTime = Math.max(1, Math.ceil((p.excerpt?.split(/\s+/).length ?? 0) / 50));
                    return (
                      <Link
                        key={p.slug}
                        to={`/blog/${p.slug}`}
                        className="group surface-card card-hover p-5 hover:border-brand-500/40 h-full flex flex-col focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 focus-visible:ring-offset-2"
                      >
                        <div className="flex flex-wrap gap-1 mb-2">
                          {p.tags.slice(0, 2).map((t) => (
                            <span
                              key={t}
                              className="rounded border border-slate-200 dark:border-[rgb(var(--border-400))] bg-slate-50 dark:bg-[rgb(var(--surface-200)/0.6)] px-2 py-0.5 text-micro font-mono text-slate-500 dark:text-slate-400"
                            >
                              {t}
                            </span>
                          ))}
                          {p.tags.length > 2 && (
                            <span className="text-micro font-mono text-slate-400 self-center">
                              +{p.tags.length - 2}
                            </span>
                          )}
                        </div>
                        <h3 className="font-display text-base font-bold text-slate-900 dark:text-white transition-colors group-hover:text-brand-600 dark:group-hover:text-brand-400 line-clamp-2">
                          {p.title}
                        </h3>
                        <p className="mt-1.5 text-xs text-muted leading-relaxed line-clamp-2 flex-1">{p.excerpt}</p>
                        <div className="mt-3 text-mini font-mono text-slate-400">
                          {formatDate(p.publishedAt)} · {relatedReadTime} min read
                        </div>
                      </Link>
                    );
                  })}
                </div>
              </section>
            )}
          </>
        )}
      </DataState>
    </article>
  );
}
