/**
 * Lazy runtime loader for the MITRE ATT&CK id index.
 *
 * The index (~470 KB of generated JSON, 5376 ids) used to be bundled as a
 * TypeScript module (`api/src/data/attack-id-index.ts`), which pushed the
 * Worker script past the 3 MiB free-plan size limit. It now ships as a
 * static asset (`/data/attack-id-index.json`, generated by
 * `scripts/build-attack-index.mjs`) and is fetched through the ASSETS
 * binding on first use, then memoised for the isolate's lifetime.
 *
 * Regenerate both copies with: node scripts/build-attack-index.mjs
 */
import type { Env } from '../env';

export interface AttackRef {
  id: string;
  col: 'e' | 'i' | 'm';
  tac?: string;
}

export type AttackIdIndex = Record<string, AttackRef>;

let cached: AttackIdIndex | null = null;
let pending: Promise<AttackIdIndex> | null = null;

export function loadAttackIdIndex(env: Env): Promise<AttackIdIndex> {
  if (cached) return Promise.resolve(cached);
  if (!pending) {
    pending = (async () => {
      const res = await env.ASSETS.fetch(new Request('https://assets.internal/data/attack-id-index.json'));
      if (!res.ok)
        throw new Error(`attack-id-index asset missing (${res.status}) — run scripts/build-attack-index.mjs`);
      const idx = (await res.json()) as AttackIdIndex;
      cached = idx;
      return idx;
    })().catch((err) => {
      pending = null;
      throw err;
    });
  }
  return pending;
}

/**
 * Sync accessor for code paths that cannot await (pure helpers, sort
 * comparators). Returns null before the first successful load — callers
 * decide whether to degrade gracefully or fail loudly. The /api/v1/*
 * preload middleware guarantees a loaded index on HTTP paths; cron paths
 * preloading explicitly: warmIntelBundles().
 */
export function loadedAttackIdIndexOrNull(): AttackIdIndex | null {
  return cached;
}

/** Test hook — clears the memoised index. */
export function _resetAttackIdIndexForTests(): void {
  cached = null;
  pending = null;
}
