#!/usr/bin/env node
/**
 * Generate TypeScript types from the API's OpenAPI spec.
 *
 * Reads the spec from `OPENAPI_URL` (default: production), pipes it
 * through `openapi-typescript`, and writes the resulting types to
 * `src/lib/api-types.ts` for the frontend to import.
 *
 * Usage:
 *   npm run codegen                    # fetch from production
 *   OPENAPI_URL=http://localhost:8787/api/v1/openapi.json npm run codegen   # local dev
 *   npm run codegen:check              # verify generated file is up to date (CI)
 *
 * Why a script, not a build step:
 *   - The generated file is committed to the repo, so editors and
 *     `tsc` see the types without running codegen first.
 *   - The CI `codegen:check` script is the source-of-truth gate that
 *     catches drift between the spec and the committed types.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUT = resolve(ROOT, 'src/lib/api-types.ts');
const OPENAPI_URL = process.env.OPENAPI_URL ?? 'https://pranithjain.qzz.io/api/v1/openapi.json';
const CHECK = process.argv.includes('--check');

function fetchSpec(url) {
  console.log(`[codegen] fetching ${url}`);
  const res = spawnSync('curl', ['-fsSL', '--max-time', '30', url], { encoding: 'utf8' });
  if (res.status !== 0) {
    throw new Error(`failed to fetch OpenAPI spec from ${url}: ${res.stderr || res.stdout}`);
  }
  return res.stdout;
}

function generateTypes(specJson) {
  // Validate that the response is JSON before piping it through the
  // generator. A 200 with an HTML error page (e.g. when auth is
  // misconfigured) would otherwise produce garbage types.
  try {
    JSON.parse(specJson);
  } catch (e) {
    throw new Error(`OpenAPI response is not valid JSON: ${e.message}`);
  }
  // The openapi-typescript v7 CLI takes the spec as a positional arg
  // (or via stdin with no arg). We stage the spec in a temp file so
  // we can use the file path form, and read the output from a second
  // temp file. Both are removed on exit.
  const dir = mkdtempSync(join(tmpdir(), 'codegen-'));
  const inputPath = join(dir, 'openapi.json');
  const outputPath = join(dir, 'api-types.ts');
  writeFileSync(inputPath, specJson);
  try {
    const res = spawnSync(
      resolve(ROOT, 'node_modules/.bin/openapi-typescript'),
      [inputPath, '--output', outputPath, '--enum', '--immutable'],
      { encoding: 'utf8' }
    );
    if (res.status !== 0) {
      throw new Error(`openapi-typescript failed: ${res.stderr || res.stdout}`);
    }
    return readFileSync(outputPath, 'utf8');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function header(generatedAt) {
  return `// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
// Generated by \`npm run codegen\` from:
//   ${OPENAPI_URL}
//
// Generated at: ${generatedAt}
//
// Re-run \`npm run codegen\` after changing the OpenAPI spec at
// api/src/lib/openapi.ts. The CI step \`npm run codegen:check\` will
// fail if this file drifts from the live spec.

`;
}

function main() {
  const spec = fetchSpec(OPENAPI_URL);
  const generated = generateTypes(spec);
  const body = header(new Date().toISOString()) + generated;
  if (CHECK) {
    if (!existsSync(OUT)) {
      throw new Error(`${OUT} does not exist — run \`npm run codegen\` first`);
    }
    const existing = readFileSync(OUT, 'utf8');
    if (existing !== body) {
      throw new Error(
        `${OUT} is out of date with the live OpenAPI spec.\n` +
          `Re-run \`npm run codegen\` and commit the result.`
      );
    }
    console.log('[codegen] generated types are up to date');
    return;
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body);
  console.log(`[codegen] wrote ${OUT} (${body.length.toLocaleString()} bytes)`);
}

main();
