/**
 * Self-host the three Google Fonts families (privacy-first: no third-party
 * request leaks the visitor's IP to Google; also removes a cross-origin
 * preconnect + CSS round-trip and lets the CSP drop googleapis/gstatic).
 *
 * Fetches the css2 stylesheet, keeps only the latin + latin-ext @font-face
 * blocks (English-only app), downloads each woff2 into public/fonts/, and
 * writes public/fonts/fonts.css with the src URLs rewritten to local paths.
 *
 * Run: node scripts/fetch-fonts.mjs   (re-run to refresh; output is committed)
 */
import { writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');
mkdirSync(OUT, { recursive: true });
// Clean stale output so removed/renamed weights don't linger as committed assets.
for (const f of readdirSync(OUT)) {
  if (f.endsWith('.woff2') || f === 'fonts.css') rmSync(join(OUT, f));
}

// A modern desktop UA so Google serves woff2 (not the older ttf/eot variants).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600..800&family=Hanken+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap';
const KEEP = new Set(['latin', 'latin-ext']);

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Dedupe by file CONTENT: Hanken/JetBrains are variable fonts, so Google serves
// one woff2 per subset and emits a pinned-weight @font-face per weight, all
// pointing at byte-identical bytes. Writing each once (content-hashed name) and
// letting every weight block share the file cuts ~224KB of redundant cold-load
// downloads with zero rendering change, and the hashed name is safe to cache
// immutably (see public/_headers `/fonts/*.woff2`).
const rules = [];
const byHash = new Map(); // contentHash -> filename
for (const chunk of css.split('/* ').slice(1)) {
  const range = chunk.slice(0, chunk.indexOf(' */')).trim();
  if (!KEEP.has(range)) continue;
  let face = chunk.slice(chunk.indexOf('@font-face'));
  face = face.slice(0, face.indexOf('}') + 1);
  const url = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  const fam = (face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font').toLowerCase().replace(/\s+/g, '-');
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const hash = createHash('sha256').update(buf).digest('hex').slice(0, 8);
  let name = byHash.get(hash);
  if (!name) {
    name = `${fam}-${range}-${hash}.woff2`;
    writeFileSync(join(OUT, name), buf);
    byHash.set(hash, name);
  }
  let rule = face.replace(url, `/fonts/${name}`);
  if (!/font-display\s*:/.test(rule)) rule = rule.replace('@font-face {', '@font-face {\n  font-display: swap;');
  rules.push(rule.trim());
}

const header = `/* Self-hosted Google Fonts (latin + latin-ext subset) — generated by scripts/fetch-fonts.mjs.\n   Privacy-first: no third-party request, no cross-origin font CSS/woff2 round-trip.\n   woff2 are content-hashed + deduped (variable fonts share one file across weights). */\n\n`;
writeFileSync(join(OUT, 'fonts.css'), header + rules.join('\n\n') + '\n');
console.log(`Wrote ${rules.length} @font-face rules + ${byHash.size} unique woff2 files to public/fonts/`);
