/**
 * Self-host the three Google Fonts families (privacy-first: no third-party
 * request leaks the visitor's IP to Google; also removes a cross-origin
 * preconnect + CSS round-trip and lets the CSP drop googleapis/gstatic).
 *
 * Fetches the css2 stylesheet, keeps EVERY subset @font-face block Google
 * serves (latin, latin-ext, cyrillic, cyrillic-ext, greek, vietnamese, …),
 * downloads each woff2 into public/fonts/, and writes public/fonts/fonts.css
 * with the src URLs rewritten to local paths. Subsets are lazy-loaded by
 * unicode-range, so this is an exact drop-in for the old Google CSS.
 *
 * All network fetches complete and are validated (res.ok) BEFORE the committed
 * output is deleted and rewritten, so a failed/partial run never wipes the
 * committed fonts.
 *
 * Run: node scripts/fetch-fonts.mjs   (re-run to refresh; output is committed)
 */
import { writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');

// A modern desktop UA so Google serves woff2 (not the older ttf/eot variants).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600..800&family=Hanken+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap';

async function fetchOk(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fetch ${url} -> HTTP ${res.status}`);
  return res;
}

const css = await (await fetchOk(CSS_URL)).text();

// Keep EVERY subset Google serves for these families. Subsetted @font-face are
// lazy-loaded by unicode-range, so a visitor downloads a subset only when a
// matching glyph appears — normal latin pages still fetch latin alone. Keeping
// them all makes this an exact, no-regression drop-in for the old Google CSS,
// which served Cyrillic / Greek / Vietnamese on demand (e.g. JetBrains Mono is
// the brand mono for the homograph DFIR tools that DISPLAY Cyrillic/Greek
// lookalike domains — Punycode.tsx, IocExtractor.tsx).
//
// Dedupe by file CONTENT: Hanken/JetBrains are variable fonts, so Google serves
// one woff2 per subset and emits a pinned-weight @font-face per weight, all
// pointing at byte-identical bytes. Writing each once (content-hashed name) and
// letting every weight block share the file cuts redundant cold-load downloads
// with zero rendering change, and the hashed name is safe to cache immutably
// (see public/_headers `/fonts/*.woff2`).
const rules = [];
const files = new Map(); // filename -> Buffer (one entry per unique content)
const byHash = new Map(); // contentHash -> filename
for (const chunk of css.split('/* ').slice(1)) {
  const range = chunk.slice(0, chunk.indexOf(' */')).trim();
  if (!chunk.includes('@font-face')) continue; // skip any non-font chunk
  let face = chunk.slice(chunk.indexOf('@font-face'));
  face = face.slice(0, face.indexOf('}') + 1);
  const url = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  const fam = (face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font').toLowerCase().replace(/\s+/g, '-');
  const buf = Buffer.from(await (await fetchOk(url)).arrayBuffer());
  const hash = createHash('sha256').update(buf).digest('hex').slice(0, 8);
  let name = byHash.get(hash);
  if (!name) {
    name = `${fam}-${range}-${hash}.woff2`;
    byHash.set(hash, name);
    files.set(name, buf);
  }
  let rule = face.replace(url, `/fonts/${name}`);
  if (!/font-display\s*:/.test(rule)) rule = rule.replace('@font-face {', '@font-face {\n  font-display: swap;');
  rules.push(rule.trim());
}

if (!rules.length) throw new Error('no @font-face rules parsed — aborting without touching committed fonts');

// Every fetch succeeded — only now is it safe to replace the committed output.
mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) {
  if (f.endsWith('.woff2') || f === 'fonts.css') rmSync(join(OUT, f));
}
for (const [name, buf] of files) writeFileSync(join(OUT, name), buf);

const header = `/* Self-hosted Google Fonts (all subsets Google serves: latin, latin-ext, cyrillic, cyrillic-ext, greek, vietnamese, …) — generated by scripts/fetch-fonts.mjs.\n   Privacy-first: no third-party request, no cross-origin font CSS/woff2 round-trip.\n   Subsets lazy-load by unicode-range; woff2 are content-hashed + deduped (variable fonts share one file across weights). */\n\n`;
writeFileSync(join(OUT, 'fonts.css'), header + rules.join('\n\n') + '\n');
console.log(`Wrote ${rules.length} @font-face rules + ${files.size} unique woff2 files to public/fonts/`);
