import type { PulseEvent, PulseKind, TechLocation, GeopoliticalLocation } from './types';
import { hoursAgo } from './shared';

/* ─── Tech Infrastructure (Static Data — Data Centers, IXPs, Cloud Regions) ── */

const TECH_LOCATIONS: TechLocation[] = [
  // Major Data Centers
  {
    name: 'Ashburn Data Center Alley',
    lat: 39.04,
    lng: -77.49,
    type: 'datacenter',
    operator: 'Equinix/Digital Realty',
    country: 'US',
  },
  { name: 'Northern Virginia', lat: 38.95, lng: -77.45, type: 'datacenter', operator: 'AWS/Azure/GCP', country: 'US' },
  { name: 'Dallas Data Center Hub', lat: 32.78, lng: -96.8, type: 'datacenter', operator: 'Equinix', country: 'US' },
  {
    name: 'Chicago Data Center',
    lat: 41.88,
    lng: -87.63,
    type: 'datacenter',
    operator: 'QTS/Digital Realty',
    country: 'US',
  },
  { name: 'Silicon Valley', lat: 37.39, lng: -122.08, type: 'datacenter', operator: 'Equinix/CoreSite', country: 'US' },
  { name: 'Portland Data Center', lat: 45.52, lng: -122.68, type: 'datacenter', operator: 'Infomart', country: 'US' },
  {
    name: 'London Data Center',
    lat: 51.51,
    lng: -0.13,
    type: 'datacenter',
    operator: 'Equinix/Digital Realty',
    country: 'GB',
  },
  { name: 'Amsterdam AMS-IX', lat: 52.37, lng: 4.9, type: 'datacenter', operator: 'Equinix/Nikhef', country: 'NL' },
  { name: 'Frankfurt DE-CIX', lat: 50.11, lng: 8.68, type: 'datacenter', operator: 'Equinix', country: 'DE' },
  { name: 'Paris Data Center', lat: 48.86, lng: 2.35, type: 'datacenter', operator: 'Equinix', country: 'FR' },
  { name: 'Tokyo Data Center', lat: 35.68, lng: 139.69, type: 'datacenter', operator: 'Equinix/NTT', country: 'JP' },
  { name: 'Singapore Data Center', lat: 1.35, lng: 103.82, type: 'datacenter', operator: 'Equinix', country: 'SG' },
  { name: 'Sydney Data Center', lat: -33.87, lng: 151.21, type: 'datacenter', operator: 'Equinix', country: 'AU' },
  { name: 'Mumbai Data Center', lat: 19.08, lng: 72.88, type: 'datacenter', operator: 'Equinix', country: 'IN' },
  { name: 'São Paulo Data Center', lat: -23.55, lng: -46.63, type: 'datacenter', operator: 'Equinix', country: 'BR' },
  // Major Internet Exchange Points
  { name: 'DE-CIX Frankfurt', lat: 50.11, lng: 8.68, type: 'ixp', operator: 'DE-CIX', country: 'DE' },
  { name: 'AMS-IX Amsterdam', lat: 52.37, lng: 4.9, type: 'ixp', operator: 'AMS-IX', country: 'NL' },
  { name: 'LINX London', lat: 51.51, lng: -0.13, type: 'ixp', operator: 'LINX', country: 'GB' },
  { name: 'IX.br São Paulo', lat: -23.55, lng: -46.63, type: 'ixp', operator: 'IX.br', country: 'BR' },
  { name: 'JPNAP Tokyo', lat: 35.68, lng: 139.69, type: 'ixp', operator: 'JPNAP', country: 'JP' },
  { name: 'Equinix Ashburn', lat: 39.04, lng: -77.49, type: 'ixp', operator: 'Equinix IX', country: 'US' },
  // Cloud Provider Regions
  { name: 'AWS us-east-1', lat: 39.04, lng: -77.49, type: 'cloud_region', operator: 'AWS', country: 'US' },
  { name: 'AWS eu-west-1', lat: 53.35, lng: -6.26, type: 'cloud_region', operator: 'AWS', country: 'IE' },
  { name: 'AWS ap-southeast-1', lat: 1.35, lng: 103.82, type: 'cloud_region', operator: 'AWS', country: 'SG' },
  { name: 'Azure East US', lat: 37.38, lng: -79.82, type: 'cloud_region', operator: 'Azure', country: 'US' },
  { name: 'Azure West Europe', lat: 52.37, lng: 4.9, type: 'cloud_region', operator: 'Azure', country: 'NL' },
  { name: 'GCP us-central1', lat: 41.26, lng: -95.86, type: 'cloud_region', operator: 'GCP', country: 'US' },
  { name: 'GCP europe-west1', lat: 50.45, lng: 3.82, type: 'cloud_region', operator: 'GCP', country: 'BE' },
  // Tech Company HQs
  { name: 'Apple Park', lat: 37.33, lng: -122.01, type: 'tech_hq', operator: 'Apple', country: 'US' },
  { name: 'Googleplex', lat: 37.42, lng: -122.08, type: 'tech_hq', operator: 'Google', country: 'US' },
  { name: 'Meta HQ', lat: 37.48, lng: -122.15, type: 'tech_hq', operator: 'Meta', country: 'US' },
  { name: 'Microsoft Redmond', lat: 47.64, lng: -122.14, type: 'tech_hq', operator: 'Microsoft', country: 'US' },
  { name: 'Amazon Seattle', lat: 47.62, lng: -122.34, type: 'tech_hq', operator: 'Amazon', country: 'US' },
  { name: 'NVIDIA HQ', lat: 37.37, lng: -121.97, type: 'tech_hq', operator: 'NVIDIA', country: 'US' },
  { name: 'Tesla HQ', lat: 30.22, lng: -97.62, type: 'tech_hq', operator: 'Tesla', country: 'US' },
  { name: 'Samsung HQ', lat: 37.51, lng: 127.06, type: 'tech_hq', operator: 'Samsung', country: 'KR' },
  { name: 'Huawei HQ', lat: 22.55, lng: 114.07, type: 'tech_hq', operator: 'Huawei', country: 'CN' },
  // Startup Hubs
  { name: 'Silicon Valley', lat: 37.39, lng: -122.08, type: 'startup_hub', operator: 'Y Combinator', country: 'US' },
  { name: 'San Francisco', lat: 37.77, lng: -122.42, type: 'startup_hub', operator: 'Tech Hub', country: 'US' },
  { name: 'New York', lat: 40.71, lng: -74.01, type: 'startup_hub', operator: 'Tech Hub', country: 'US' },
  { name: 'London', lat: 51.51, lng: -0.13, type: 'startup_hub', operator: 'Tech Hub', country: 'GB' },
  { name: 'Berlin', lat: 52.52, lng: 13.41, type: 'startup_hub', operator: 'Tech Hub', country: 'DE' },
  { name: 'Tel Aviv', lat: 32.09, lng: 34.78, type: 'startup_hub', operator: 'Tech Hub', country: 'IL' },
  { name: 'Bangalore', lat: 12.97, lng: 77.59, type: 'startup_hub', operator: 'Tech Hub', country: 'IN' },
  { name: 'Shenzhen', lat: 22.54, lng: 114.06, type: 'startup_hub', operator: 'Tech Hub', country: 'CN' },
  { name: 'Singapore', lat: 1.35, lng: 103.82, type: 'startup_hub', operator: 'Tech Hub', country: 'SG' },
  { name: 'Seoul', lat: 37.57, lng: 126.98, type: 'startup_hub', operator: 'Tech Hub', country: 'KR' },
];

const TECH_KIND_MAP: Record<string, PulseKind> = {
  datacenter: 'tech_news',
  ixp: 'tech_news',
  cloud_region: 'tech_news',
  tech_hq: 'tech_news',
  startup_hub: 'tech_news',
};

const TECH_SEVERITY_MAP: Record<string, PulseEvent['severity']> = {
  datacenter: 'low',
  ixp: 'medium',
  cloud_region: 'low',
  tech_hq: 'low',
  startup_hub: 'low',
};

export function getTechInfrastructureEvents(): PulseEvent[] {
  return TECH_LOCATIONS.map((loc, idx) => ({
    id: `tech-${loc.type}-${idx}-${loc.name.replace(/\s+/g, '-').toLowerCase()}`,
    kind: TECH_KIND_MAP[loc.type] ?? 'tech_news',
    title: loc.name,
    description: `${loc.type.replace('_', ' ')} · ${loc.operator ?? loc.country}`,
    lat: loc.lat,
    lng: loc.lng,
    timestamp: hoursAgo(48),
    severity: TECH_SEVERITY_MAP[loc.type] ?? 'low',
    source: 'Static Data',
    country: loc.country,
  }));
}

/* ─── Geopolitical Hotspots (Static Data — Conflicts, Sanctions, Military) ── */

const GEOPOLITICAL_LOCATIONS: GeopoliticalLocation[] = [
  // Active Conflict Zones (2024-2026)
  {
    name: 'Ukraine-Russia Front Line',
    lat: 48.5,
    lng: 37.5,
    type: 'conflict_zone',
    description: 'Active military conflict zone',
    country: 'UA',
    severity: 'critical',
  },
  {
    name: 'Gaza Strip',
    lat: 31.5,
    lng: 34.47,
    type: 'conflict_zone',
    description: 'Active conflict zone',
    country: 'PS',
    severity: 'critical',
  },
  {
    name: 'Sudan Conflict Zone',
    lat: 15.5,
    lng: 32.5,
    type: 'conflict_zone',
    description: 'Civil war and humanitarian crisis',
    country: 'SD',
    severity: 'critical',
  },
  {
    name: 'Myanmar Conflict',
    lat: 20.0,
    lng: 96.0,
    type: 'conflict_zone',
    description: 'Ongoing civil conflict',
    country: 'MM',
    severity: 'high',
  },
  {
    name: 'Yemen Conflict',
    lat: 15.5,
    lng: 48.0,
    type: 'conflict_zone',
    description: 'Ongoing conflict and Houthi attacks',
    country: 'YE',
    severity: 'high',
  },
  {
    name: 'Ethiopia-Tigray',
    lat: 13.5,
    lng: 39.5,
    type: 'conflict_zone',
    description: 'Post-conflict instability',
    country: 'ET',
    severity: 'high',
  },
  {
    name: 'Somalia Al-Shabaab',
    lat: 2.0,
    lng: 45.3,
    type: 'conflict_zone',
    description: 'Insurgency and counter-terrorism',
    country: 'SO',
    severity: 'high',
  },
  {
    name: 'Sahel Region',
    lat: 15.0,
    lng: 0.0,
    type: 'conflict_zone',
    description: 'Mali, Burkina Faso, Niger instability',
    country: 'ML',
    severity: 'high',
  },
  {
    name: 'Haiti Gang Violence',
    lat: 18.5,
    lng: -72.3,
    type: 'conflict_zone',
    description: 'Gang violence and instability',
    country: 'HT',
    severity: 'high',
  },
  {
    name: 'Syria Northeast',
    lat: 36.5,
    lng: 40.0,
    type: 'conflict_zone',
    description: 'Ongoing instability',
    country: 'SY',
    severity: 'medium',
  },

  // Sanctioned Countries
  {
    name: 'Russia',
    lat: 61.52,
    lng: 105.32,
    type: 'sanctioned_country',
    description: 'Heavily sanctioned by US, EU, UK, others',
    country: 'RU',
    severity: 'high',
  },
  {
    name: 'Iran',
    lat: 32.43,
    lng: 53.68,
    type: 'sanctioned_country',
    description: 'Comprehensive sanctions',
    country: 'IR',
    severity: 'high',
  },
  {
    name: 'North Korea',
    lat: 40.34,
    lng: 127.51,
    type: 'sanctioned_country',
    description: 'Maximum pressure sanctions',
    country: 'KP',
    severity: 'critical',
  },
  {
    name: 'Syria',
    lat: 34.8,
    lng: 38.99,
    type: 'sanctioned_country',
    description: 'Caesar Act sanctions',
    country: 'SY',
    severity: 'high',
  },
  {
    name: 'Venezuela',
    lat: 6.42,
    lng: -66.59,
    type: 'sanctioned_country',
    description: 'Sectoral sanctions',
    country: 'VE',
    severity: 'medium',
  },
  {
    name: 'Cuba',
    lat: 21.52,
    lng: -80.0,
    type: 'sanctioned_country',
    description: 'US embargo',
    country: 'CU',
    severity: 'medium',
  },
  {
    name: 'Belarus',
    lat: 53.71,
    lng: 27.95,
    type: 'sanctioned_country',
    description: 'Sanctions for enabling Russia',
    country: 'BY',
    severity: 'medium',
  },
  {
    name: 'Myanmar',
    lat: 21.91,
    lng: 95.96,
    type: 'sanctioned_country',
    description: 'Sanctions post-coup',
    country: 'MM',
    severity: 'medium',
  },

  // Major Military Bases (key strategic locations)
  {
    name: 'Naval Station Norfolk',
    lat: 36.95,
    lng: -76.29,
    type: 'military_base',
    description: 'Largest naval base in the world',
    country: 'US',
    severity: 'low',
  },
  {
    name: 'Ramstein Air Base',
    lat: 49.44,
    lng: 7.6,
    type: 'military_base',
    description: 'US Air Force in Europe',
    country: 'DE',
    severity: 'low',
  },
  {
    name: 'Camp Humphreys',
    lat: 36.97,
    lng: 127.03,
    type: 'military_base',
    description: 'Largest US overseas base',
    country: 'KR',
    severity: 'low',
  },
  {
    name: 'Yokosuka Naval Base',
    lat: 35.33,
    lng: 139.67,
    type: 'military_base',
    description: 'US 7th Fleet headquarters',
    country: 'JP',
    severity: 'low',
  },
  {
    name: 'Diego Garcia',
    lat: -7.32,
    lng: 72.42,
    type: 'military_base',
    description: 'Strategic Indian Ocean base',
    country: 'IO',
    severity: 'low',
  },
  {
    name: 'Guantánamo Bay',
    lat: 19.93,
    lng: -75.15,
    type: 'military_base',
    description: 'US Naval Station',
    country: 'CU',
    severity: 'low',
  },
  {
    name: 'Incirlik Air Base',
    lat: 37.0,
    lng: 35.43,
    type: 'military_base',
    description: 'NATO base in Turkey',
    country: 'TR',
    severity: 'low',
  },
  {
    name: 'Pine Gap',
    lat: -23.8,
    lng: 133.74,
    type: 'military_base',
    description: 'Joint US-Australia facility',
    country: 'AU',
    severity: 'low',
  },

  // Nuclear Sites
  {
    name: 'Chernobyl Exclusion Zone',
    lat: 51.39,
    lng: 30.1,
    type: 'nuclear_site',
    description: 'Former nuclear plant',
    country: 'UA',
    severity: 'medium',
  },
  {
    name: 'Zaporizhzhia Nuclear Plant',
    lat: 47.51,
    lng: 35.59,
    type: 'nuclear_site',
    description: 'Largest nuclear plant in Europe (occupied)',
    country: 'UA',
    severity: 'critical',
  },
  {
    name: 'Fukushima Daiichi',
    lat: 37.42,
    lng: 141.03,
    type: 'nuclear_site',
    description: 'Decommissioning site',
    country: 'JP',
    severity: 'medium',
  },
  {
    name: 'Bushehr Nuclear Plant',
    lat: 28.83,
    lng: 50.88,
    type: 'nuclear_site',
    description: 'Iran nuclear facility',
    country: 'IR',
    severity: 'high',
  },
  {
    name: 'Natanz Enrichment',
    lat: 33.72,
    lng: 51.72,
    type: 'nuclear_site',
    description: 'Iran enrichment facility',
    country: 'IR',
    severity: 'high',
  },
  {
    name: 'Yongbyon Nuclear',
    lat: 39.8,
    lng: 125.76,
    type: 'nuclear_site',
    description: 'North Korea nuclear complex',
    country: 'KP',
    severity: 'critical',
  },
  {
    name: 'Dimona Nuclear',
    lat: 31.05,
    lng: 35.06,
    type: 'nuclear_site',
    description: 'Israel nuclear facility',
    country: 'IL',
    severity: 'medium',
  },
  {
    name: 'Sellafield',
    lat: 54.42,
    lng: -3.5,
    type: 'nuclear_site',
    description: 'UK nuclear reprocessing',
    country: 'GB',
    severity: 'low',
  },

  // Disputed Territories
  {
    name: 'Crimea',
    lat: 45.35,
    lng: 34.0,
    type: 'disputed_territory',
    description: 'Annexed by Russia, claimed by Ukraine',
    country: 'UA',
    severity: 'high',
  },
  {
    name: 'Taiwan Strait',
    lat: 24.0,
    lng: 119.0,
    type: 'disputed_territory',
    description: 'Cross-strait tensions',
    country: 'TW',
    severity: 'high',
  },
  {
    name: 'Kashmir',
    lat: 34.0,
    lng: 76.0,
    type: 'disputed_territory',
    description: 'India-Pakistan dispute',
    country: 'IN',
    severity: 'medium',
  },
  {
    name: 'South China Sea',
    lat: 15.0,
    lng: 115.0,
    type: 'disputed_territory',
    description: 'Territorial disputes',
    country: 'CN',
    severity: 'medium',
  },
  {
    name: 'Golan Heights',
    lat: 33.0,
    lng: 35.8,
    type: 'disputed_territory',
    description: 'Occupied by Israel',
    country: 'SY',
    severity: 'medium',
  },
  {
    name: 'Western Sahara',
    lat: 24.5,
    lng: -13.0,
    type: 'disputed_territory',
    description: 'Morocco-Polisario dispute',
    country: 'MA',
    severity: 'low',
  },
  {
    name: 'Transnistria',
    lat: 47.25,
    lng: 29.4,
    type: 'disputed_territory',
    description: 'Moldova breakaway region',
    country: 'MD',
    severity: 'medium',
  },
  {
    name: 'Nagorno-Karabakh',
    lat: 39.8,
    lng: 46.75,
    type: 'disputed_territory',
    description: 'Former conflict zone',
    country: 'AZ',
    severity: 'medium',
  },
];

const GEO_KIND_MAP: Record<string, PulseKind> = {
  conflict_zone: 'war_room',
  sanctioned_country: 'geopolitical',
  military_base: 'geopolitical',
  nuclear_site: 'geopolitical',
  disputed_territory: 'geopolitical',
};

export function getGeopoliticalEvents(): PulseEvent[] {
  return GEOPOLITICAL_LOCATIONS.map((loc, idx) => ({
    id: `geo-${loc.type}-${idx}-${loc.name.replace(/\s+/g, '-').toLowerCase()}`,
    kind: GEO_KIND_MAP[loc.type] ?? 'geopolitical',
    title: loc.name,
    description: `${loc.type.replace('_', ' ')} · ${loc.description}`,
    lat: loc.lat + (Math.random() - 0.5) * 1.5,
    lng: loc.lng + (Math.random() - 0.5) * 2,
    timestamp: hoursAgo(48),
    severity: loc.severity,
    source: 'Geopolitical Intel',
    country: loc.country,
  }));
}

/* ─── Undersea Cables (Major Landing Points) ──────────────────────────── */

const CABLE_LOCATIONS = [
  { name: 'TAT-14 Landing (NJ)', lat: 40.44, lng: -74.0, cable: 'TAT-14' },
  { name: 'MAREA Landing (VA)', lat: 36.85, lng: -76.0, cable: 'MAREA' },
  { name: 'AC-1 Landing (NY)', lat: 40.65, lng: -74.05, cable: 'AC-1' },
  { name: 'SEA-ME-WE 3 (Singapore)', lat: 1.26, lng: 103.84, cable: 'SEA-ME-WE 3' },
  { name: 'SEA-ME-WE 4 (Marseille)', lat: 43.3, lng: 5.37, cable: 'SEA-ME-WE 4' },
  { name: 'FLAG/REACH (Tokyo)', lat: 35.62, lng: 139.77, cable: 'FLAG' },
  { name: 'APCN-2 (Hong Kong)', lat: 22.28, lng: 114.16, cable: 'APCN-2' },
  { name: 'SAFE (South Africa)', lat: -33.9, lng: 18.42, cable: 'SAFE' },
  { name: 'SAT-3/WASC (Lisbon)', lat: 38.72, lng: -9.14, cable: 'SAT-3' },
  { name: 'WACS (London)', lat: 51.45, lng: 0.0, cable: 'WACS' },
  { name: 'EIG (Mumbai)', lat: 19.0, lng: 72.85, cable: 'EIG' },
  { name: 'Unity (LA)', lat: 33.74, lng: -118.29, cable: 'Unity' },
  { name: 'Pacific Crossing (OR)', lat: 46.15, lng: -123.9, cable: 'PC-1' },
  { name: 'AAG (Los Angeles)', lat: 33.75, lng: -118.3, cable: 'AAG' },
  { name: 'JUPITER (Tokyo)', lat: 35.3, lng: 139.78, cable: 'JUPITER' },
];

export function getCableEvents(): PulseEvent[] {
  return CABLE_LOCATIONS.map((c, idx) => ({
    id: `cable-${idx}-${c.cable}`,
    kind: 'tech_news' as const,
    title: c.name,
    description: `Undersea cable landing · ${c.cable}`,
    lat: c.lat,
    lng: c.lng,
    timestamp: hoursAgo(48),
    severity: 'low' as const,
    source: 'Submarine Cable Map',
  }));
}

/* ─── Stock Exchanges & Financial Centers ──────────────────────────────── */

const FINANCIAL_LOCATIONS = [
  // Stock Exchanges
  { name: 'NYSE', lat: 40.71, lng: -74.01, type: 'exchange', country: 'US' },
  { name: 'NASDAQ', lat: 40.76, lng: -73.98, type: 'exchange', country: 'US' },
  { name: 'LSE', lat: 51.51, lng: -0.09, type: 'exchange', country: 'GB' },
  { name: 'Tokyo SE', lat: 35.68, lng: 139.77, type: 'exchange', country: 'JP' },
  { name: 'Shanghai SE', lat: 31.23, lng: 121.47, type: 'exchange', country: 'CN' },
  { name: 'Hong Kong EX', lat: 22.28, lng: 114.16, type: 'exchange', country: 'HK' },
  { name: 'Euronext', lat: 48.86, lng: 2.34, type: 'exchange', country: 'FR' },
  { name: 'Shenzhen SE', lat: 22.54, lng: 114.06, type: 'exchange', country: 'CN' },
  { name: 'Toronto SE', lat: 43.65, lng: -79.38, type: 'exchange', country: 'CA' },
  { name: 'BSE India', lat: 18.93, lng: 72.84, type: 'exchange', country: 'IN' },
  { name: 'Deutsche Börse', lat: 50.11, lng: 8.68, type: 'exchange', country: 'DE' },
  { name: 'KRX Seoul', lat: 37.57, lng: 126.98, type: 'exchange', country: 'KR' },
  { name: 'ASX Sydney', lat: -33.87, lng: 151.21, type: 'exchange', country: 'AU' },
  { name: 'B3 São Paulo', lat: -23.55, lng: -46.63, type: 'exchange', country: 'BR' },
  { name: 'Johannesburg SE', lat: -26.2, lng: 28.05, type: 'exchange', country: 'ZA' },
  // Financial Centers
  { name: 'Wall Street', lat: 40.71, lng: -74.01, type: 'financial', country: 'US' },
  { name: 'City of London', lat: 51.51, lng: -0.08, type: 'financial', country: 'GB' },
  { name: 'Singapore CBD', lat: 1.28, lng: 103.85, type: 'financial', country: 'SG' },
  { name: 'Hong Kong Central', lat: 22.28, lng: 114.16, type: 'financial', country: 'HK' },
  { name: 'Zurich Banking', lat: 47.37, lng: 8.54, type: 'financial', country: 'CH' },
  { name: 'Dubai DIFC', lat: 25.22, lng: 55.28, type: 'financial', country: 'AE' },
  { name: 'Frankfurt Banking', lat: 50.11, lng: 8.68, type: 'financial', country: 'DE' },
  { name: 'Tokyo Marunouchi', lat: 35.68, lng: 139.77, type: 'financial', country: 'JP' },
];

export function getFinancialEvents(): PulseEvent[] {
  return FINANCIAL_LOCATIONS.map((f, idx) => ({
    id: `fin-${f.type}-${idx}-${f.name.replace(/\s+/g, '-').toLowerCase()}`,
    kind: 'geopolitical' as const,
    title: f.name,
    description: `${f.type === 'exchange' ? 'Stock Exchange' : 'Financial Center'} · ${f.country}`,
    lat: f.lat,
    lng: f.lng,
    timestamp: hoursAgo(48),
    severity: 'low' as const,
    source: 'Financial Data',
    country: f.country,
  }));
}
