import tseslint from 'typescript-eslint';

export default tseslint.config(
  { ignores: ['**/*.test.ts', '**/*.d.ts'] },
  {
    extends: [
      ...tseslint.configs.recommended,
    ],
    files: ['src/**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        Crypto: 'readonly',
        CryptoKey: 'readonly',
        SubtleCrypto: 'readonly',
        Cache: 'readonly',
        caches: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        ReadableStream: 'readonly',
        WritableStream: 'readonly',
        TransformStream: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        RequestInfo: 'readonly',
        RequestInit: 'readonly',
        ResponseInit: 'readonly',
        structuredClone: 'readonly',
        D1Database: 'readonly',
        D1Result: 'readonly',
        D1PreparedStatement: 'readonly',
        KVNamespace: 'readonly',
        R2Bucket: 'readonly',
        R2Object: 'readonly',
        Queue: 'readonly',
        Fetcher: 'readonly',
        DurableObjectNamespace: 'readonly',
        DurableObject: 'readonly',
        DurableObjectState: 'readonly',
        Ai: 'readonly',
        VectorizeIndex: 'readonly',
        AnalyticsEngineDataset: 'readonly',
        Event: 'readonly',
        FetchEvent: 'readonly',
        ScheduledEvent: 'readonly',
        Buffer: 'readonly',
        process: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',

      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
      'no-unused-vars': 'off',
      'no-throw-literal': 'error',

      '@typescript-eslint/await-thenable': 'warn',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-misused-promises': 'warn',

      'no-console': 'warn',
      'prefer-const': 'warn',
      'no-var': 'warn',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'warn',
      'no-undef': 'warn',
      'no-irregular-whitespace': 'warn',
      '@typescript-eslint/prefer-as-const': 'warn',
      '@typescript-eslint/no-unnecessary-type-constraint': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
    },
  },
);
